In [1]:
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, PointStruct

import pandas as pd
import openai

In [2]:
from dotenv import load_dotenv
load_dotenv(override=True)

True

### Read sampled dataset with Amazon inventory data

In [3]:
df_items=pd.read_json('../../data/meta_Electronics_2022_2023_has_main_category_sample_1000.jsonl', lines=True)

In [4]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,Camera & Photo,GuFamily Indoor Security Camera 2K HD 360 Degr...,1.7,8,[【2K Clarity for Full Coverage Monitoring】: Th...,[2K HD Indoor Surveillance Camera Works with 2...,18.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],generic,"[Electronics, Camera & Photo, Video Surveillan...",{'Package Dimensions': '6.18 x 3.54 x 3.43 inc...,B0CBNZ93NJ,NaN,NaN,NaN
1,Cell Phones & Accessories,Tinkers Silicone Airpod Pro Case with Airtag H...,4.2,9,[Airpod Pro Keyring Case with Airtag Holder Fo...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': '2 in 1 Silicone Protective Case fo...,Tinkers,"[Electronics, Headphones, Earbuds & Accessorie...",{'Package Dimensions': '3.86 x 3.62 x 1.3 inch...,B09Q5HMPLS,NaN,NaN,NaN
2,All Electronics,Cameron sino 2200mAh 3.7V Li-ion 361-00023-13 ...,3.0,1,[Replacement for models: Garmin Pro 550 handhe...,[Cameron Sino is a brand focusing on sell batt...,25.78,[{'thumb': 'https://m.media-amazon.com/images/...,[],Cameron Sino®,[],{'Product Dimensions': '2.61 x 0.73 x 0.8 inch...,B01LZ85O5N,NaN,NaN,NaN
3,Computers,LTPRPTS Replacement Laptop LCD Back Cover Top ...,5.0,5,[1. 100% Original Brand New for Lenovo Flex 5 ...,[New Replacement for Lenovo Flex 5 15 5 15iil0...,55.68,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Installation video ONLY for IdeaPa...,LTPRPTS,"[Electronics, Computers & Accessories, Compute...",{'Product Dimensions': '13.78 x 9.84 x 3.94 in...,B0B7X9CQTF,NaN,NaN,NaN
4,Camera & Photo,ETLIN Security Camera Indoor with Smoke Detect...,4.5,112,[Security Camera Smoke Detector: 2-in-1 design...,"[Home Camera Featuring:, ●HD 1080P Video ●HD 1...",45.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],ETLIN,"[Electronics, Camera & Photo, Video Surveillan...","{'Package Dimensions': '3 x 1.1 x 1.1 inches',...",B0C6GCBXMT,NaN,NaN,NaN

In [5]:
list(df_items["features"].items())[0]

(0,
 ['【2K Clarity for Full Coverage Monitoring】: This indoor security camera boasts a 2K resolution, combined with 360-degree horizontal rotation and 105-degree vertical tilt, allowing you to effectively monitor your home. The full coverage monitoring of this home camera is not only for space,but also for time, the night vision function provides you with 24-hour continuous monitoring without interruption, so you can know what happened at night.',
  '【2.4GHz&5GHzDual-Band WiFi Connection】: This home camera works with 2.4GHz & 5GHz WiFi, and easy to install, even can not install on the wall, you can just put it on the shelf or any flat area. It can be installed on the ceiling if needed. So you neither need to worry about whether this camera can connect to your network, nor distressed about how to install this camera.',
  '【Motion Detection & Tracking Alert】: Indoor security cameras for home automatically track motion when detected. When motion is sensed, the App will promptly send a real-time alert to your phone, ensuring you never miss any crucial movements.',
  '【Privacy Protection】: The data of this 2K pet camera can be stored in cloud or SD/TF card, and the highest compatible capacity for an SD card is 128GB. You can watch the vedio recorded by this dog camera. And to protect your privacy, you can set the sleep time to disable the camera.',
  '【Multi-user & Two-way Audio】: The device can be shared with others through the app, allowing them to have joint control. With the built-in microphone and speaker, controlers can communicate with the one arround the surveillance camera. We also provide 7/24 customer service, if you have any questions, please feel free to contact us.'])

In [6]:
list(df_items["images"].items())[0]

(0,
 [{'thumb': 'https://m.media-amazon.com/images/I/41kLHj6mnHL._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/41kLHj6mnHL._AC_.jpg',
   'variant': 'MAIN',
   'hi_res': 'https://m.media-amazon.com/images/I/61nfN2SWotL._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/51EFWksD7QL._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51EFWksD7QL._AC_.jpg',
   'variant': 'PT01',
   'hi_res': 'https://m.media-amazon.com/images/I/71dp-ztU1DL._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/51U87TVdKmL._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51U87TVdKmL._AC_.jpg',
   'variant': 'PT02',
   'hi_res': 'https://m.media-amazon.com/images/I/71xkh9zbuPL._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/51F85a5mdkL._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51F85a5mdkL._AC_.jpg',
   'variant': 'PT03',
   'hi_res': 'https://m.media-amazon.com/images/I/71N4+MeBiNL._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/51aBNa3j9AL._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51aBNa3j9AL._AC_.jpg',
   'variant': 'PT04',
   'hi_res': 'https://m.media-amazon.com/images/I/71oAsCPJdjL._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/51f4-monigL._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51f4-monigL._AC_.jpg',
   'variant': 'PT05',
   'hi_res': 'https://m.media-amazon.com/images/I/81MI75iV6KL._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/41KfI1-Pt9L._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/41KfI1-Pt9L._AC_.jpg',
   'variant': 'PT06',
   'hi_res': 'https://m.media-amazon.com/images/I/51W4+lVAb4L._AC_SL1500_.jpg'}])

In [7]:
def preprocess_description(row):
    return f"{row["title"]} {' '.join(row["features"])}"

In [8]:
def extract_first_large_image(row):
    try:
        return row["images"][0].get("large", "")
    except (IndexError, TypeError, KeyError):
        return ""

In [9]:
df_items["description"] = df_items.apply(preprocess_description,axis=1)
df_items["image"]=df_items.apply(extract_first_large_image,axis=1)

In [10]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author,image
0,Camera & Photo,GuFamily Indoor Security Camera 2K HD 360 Degr...,1.7,8,[【2K Clarity for Full Coverage Monitoring】: Th...,GuFamily Indoor Security Camera 2K HD 360 Degr...,18.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],generic,"[Electronics, Camera & Photo, Video Surveillan...",{'Package Dimensions': '6.18 x 3.54 x 3.43 inc...,B0CBNZ93NJ,NaN,NaN,NaN,https://m.media-amazon.com/images/I/41kLHj6mnH...
1,Cell Phones & Accessories,Tinkers Silicone Airpod Pro Case with Airtag H...,4.2,9,[Airpod Pro Keyring Case with Airtag Holder Fo...,Tinkers Silicone Airpod Pro Case with Airtag H...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': '2 in 1 Silicone Protective Case fo...,Tinkers,"[Electronics, Headphones, Earbuds & Accessorie...",{'Package Dimensions': '3.86 x 3.62 x 1.3 inch...,B09Q5HMPLS,NaN,NaN,NaN,https://m.media-amazon.com/images/I/31J5BQZchC...
2,All Electronics,Cameron sino 2200mAh 3.7V Li-ion 361-00023-13 ...,3.0,1,[Replacement for models: Garmin Pro 550 handhe...,Cameron sino 2200mAh 3.7V Li-ion 361-00023-13 ...,25.78,[{'thumb': 'https://m.media-amazon.com/images/...,[],Cameron Sino®,[],{'Product Dimensions': '2.61 x 0.73 x 0.8 inch...,B01LZ85O5N,NaN,NaN,NaN,https://m.media-amazon.com/images/I/41tSkDcUta...
3,Computers,LTPRPTS Replacement Laptop LCD Back Cover Top ...,5.0,5,[1. 100% Original Brand New for Lenovo Flex 5 ...,LTPRPTS Replacement Laptop LCD Back Cover Top ...,55.68,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Installation video ONLY for IdeaPa...,LTPRPTS,"[Electronics, Computers & Accessories, Compute...",{'Product Dimensions': '13.78 x 9.84 x 3.94 in...,B0B7X9CQTF,NaN,NaN,NaN,https://m.media-amazon.com/images/I/21+U-0xlpg...
4,Camera & Photo,ETLIN Security Camera Indoor with Smoke Detect...,4.5,112,[Security Camera Smoke Detector: 2-in-1 design...,ETLIN Security Camera Indoor with Smoke Detect...,45.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],ETLIN,"[Electronics, Camera & Photo, Video Surveillan...","{'Package Dimensions': '3 x 1.1 x 1.1 inches',...",B0C6GCBXMT,NaN,NaN,NaN,https://m.media-amazon.com/images/I/314Icv83q2...

In [11]:
df_items["description"]

0      GuFamily Indoor Security Camera 2K HD 360 Degr...
1      Tinkers Silicone Airpod Pro Case with Airtag H...
2      Cameron sino 2200mAh 3.7V Li-ion 361-00023-13 ...
3      LTPRPTS Replacement Laptop LCD Back Cover Top ...
4      ETLIN Security Camera Indoor with Smoke Detect...
                             ...
995    Zip Ties Heavy Duty(150Pcs), Cable Ties Reusab...
996    MOROVOL ATX PC Case Pre-Installed 4PCS RGB Fan...
997    Smart Watch for Women Ladies Smart Bracelet IP...
998    NTONPOWER 2 Prong Power Strip, 1875W 2 Prong t...
999    GAROGYI Bluetooth 5.1 Adapter for PC, USB Blue...
Name: description, Length: 1000, dtype: object

### Sample 50 items from dataset

In [12]:
df_sample = df_items.sample(50,random_state=42)

In [13]:
len(df_sample)

50

In [14]:
data_to_embed = df_sample[["description","image","rating_number","price","average_rating","parent_asin"]].to_dict(orient="records")

In [15]:
data_to_embed

[{'description': '2023 Upgraded 1080P WiFi Camera Motion Sound Detector for Home Office,Indoor Camera with Night Vision - Car Cameras for Surveillance - Size:1.22 x 1.22 x 1.22 inches ',
  'image': 'https://m.media-amazon.com/images/I/41wwiQiqHPL._AC_.jpg',
  'rating_number': 19,
  'price': 18.85,
  'average_rating': 2.1,
  'parent_asin': 'B0BZYSHG74'},
 {'description': '65W Replacement AC Adapter Charger for HP 15 15-f233wm 15-f272wm 15-f010wm 15-f305dx 15-af131dx Spectre X360 13-a010dx 13-4003dx 13-4103dx Pavilion 15 Laptop Notebook PC Power Supply Cord FEATURES / POWER SPECS : Only Pwr+ Chargers Have Extra Long 12 Ft Power AC/DC cords / Output 19.5V 3.33A 45W 65W / Input 100-240V / Made in Taiwan COMPATIBILITY: HP 14 15 17 M6 M7 Series 14-dq0040nr 463958-001 741727-001 740015-001 740015-003 740015-004 Envy Stream 11 13 14 PRO G2 HP Spectre x360 13 13T Split x2, 612 G1, 410 G1, Elite X2 1011 G1, x360 310 G2, ZBook 14 HP Chromebook 11 14 G1 G3 G4 Pavilion x360 14-dw1024nr; HP Notebook 15 17 Business Laptop 15-dy2024nr 15-af131dx 15-ay009dx 15-ay041wm 15-ba009dx 15-bs015dx 15-d035dx 15-f009wm 15-f010wm 15-f033wm 15-f039wm 15-f233wm 15-f272wm 15-f387wm 15-g070nr 15-r011dx 15-r029wm 15-r132wm COMPATIBILITY: HP Notebook 15, 17 Business Notebook 11-d010wm 11-d011wm 11-n010dx 13-c010nr 14-ax020wm 15-ac121dx 15-af131dx 15-ay009dx 15-ay039wm 15-ay041wm 15-d035dx 15-f009wm 15-f010wm 15-f033wm 15-f039wm 15-f211wm 15-f233wm 15-f271wm 15-f272wm 15-f305dx 15-f387wm 15-g019wm 15-g070nr 15-r011dx 15-r029wm 15-r132wm 15-bs289wm 15-f209wm 15-ba018wm 15-dy1074nr 15-cc067cl 15-cs0072wm COMPATIBILITY: P/N L24008-001 L25296-001 L25296-002 213349-109 710412-001 710413-001 719309-003 719309-001 721092-001 740015-001 740015-003 740015-004 740015-002 741727-001 741553-850 845836-850 854054-003 854054-002 854054-001 TPN-LA03 H6Y88AA H6Y89AA PA-1450-36HE PA-1650-32HE HSTNN-LA40 ADP-45FE B HSTNN-DA40 PPP009C PPP012L-E PPP012D-S SAFETY / UL LISTED: Tested, Approved and Certified by UL. UL number is unique. UL testing is authorized by OSHA - US Federal Agency / WARRANTY: 30 Days Refund - 24 Months Exchange. PWR+ is WA, USA based company. We are friendly Customer Support Experts',
  'image': 'https://m.media-amazon.com/images/I/41xi8yPrvWL._AC_.jpg',
  'rating_number': 1,
  'price': 22.99,
  'average_rating': 5.0,
  'parent_asin': 'B008FPY1VG'},
 {'description': 'Hoqqf Dual Lens Cover Compatible with Insta360 ONE X2 Screen Protector Kit, Olephobic Fingerprint-proof Screen Protector Screen Tempered Film(2Pcs Lens Guard & 1Pcs Screen Protector) 【Compatibility】Both 2 items are compatible with Insta360 ONE X2. 【9H Hardness】The screen protector and lens guard have treated with a longer tempering time, which makes the them have a higher hardness. It can prevents the camera screen and lens from high impact drops, scratches such as keys and knives, scrapes, and bumps. 【High Clarity】The screen protector and lens guard have 99.99% HD clarity. High-transparency provides high-definition clear viewing when shooting. 【Olephobic】The screen protector has Olephobic and Fingerprint-proof layers coated, which can keep it clean and clear when in use. 【Ultra Thin】The thickness of the screen protector is 0.33mm, sensitive touchscreen feeling like naked screen. 【Seamless Mount】The lens guard is paste designed, sealed, not easy to fall off. It can perfectly cover the camera lens and no need to remove when shooting. 【Package includes】Lens guard *2, screen protector *1, prying tool *1, storage case *2, cleaning cloth *2, fixing sticker *2, instruction manual *2',
  'image': 'https://m.media-amazon.com/images/I/411khozR4EL._AC_.jpg',
  'rating_number': 11,
  'price': nan,
  'average_rating': 3.1,
  'parent_asin': 'B09ZY1XS8C'},
 {'description': 'Lenovo Yoga 6 13 2-in-1 Laptop I 13.3" WUXGA IPS 100% sRGB Touchscreen I AMD 6-Core Ryzen 5 5500U (>i7-10510U) I 8GB DDR4 512GB SSD I Backlit Fingerprint HDMI Win11 Pro Dark Teal + 32GB MicroSD Card 【Enough Storage】: 8GB DDR4 SDRAM Memory, 512GB Solid State Drive 【Lenovo Yoga Laptop Ryzen 5】: AMD 6-Core Ryzen 5 5500U 【Strong Graphics and Display】: AMD Radeon Graphics Integrated | 13.3" WUXGA 1920x1200 IPS 100% sRGB Touchscreen 【External Ports and Slots】: 1 x HDMI 2.0; 2 x USB-C 3.2, 2 x USB-A 3.2 (One Always On); 1 x MicroSD card reader 【Operating System】: Windows 11 Professional, Backlit Keyboard, Fingerprint Reader, FHD 1080p & IR Privacy Camera',
  'image': 'https://m.media-amazon.com/images/I/41D1qw9dXJL._AC_.jpg',
  'rating_number': 5,
  'price': 699.0,
  'average_rating': 4.0,
  'parent_asin': 'B09V2N38K7'},
 {'description': 'Airpod Strap Necklace Holder Magnetic, Anti-Lost Pearl Lanyard Cord for Neck Compatible with AirPods 1/2/Pro The anti-lost Airpods strap equipped updated newest magnet,which have strong magnetic attraction. The Airpods leash strap are compatible for Airpods pro,1,2. This fashion chain necklace especially design for women ,girl or ladies Warranty:3 months warranty.We will provide a full refund or replacement if you have received a defective product and contact us. It hangs over the chest like a pendant necklace. It is suitable to match any style of clothing. The ultralight Airpods lanyard\xa0not only can protect your airpods ,but also it is stylish decoration necklace.',
  'image': 'https://m.media-amazon.com/images/I/31An7dfFfbL._AC_.jpg',
  'rating_number': 28,
  'price': 9.95,
  'average_rating': 3.2,
  'parent_asin': 'B09QH2G56J'},
 {'description': 'SNKIZN Universal Switching Power Supply - AC100-240V to DC5V10A, 50W Ideal for CCTV Camera Systems, Radio, LED Strip, Pixel Lights, Includes LED Driver 5V Power Supply The SNKIZN AC adapters provide protection features such as shortage protection, overload protection, and over-voltage protection (115%-135%). With an input range of 110V-220V 50/60Hz and output of 5V DC up to 30 Amps Max, the output voltage can be regulated by ±10%, from 4.5V to 5.5V. Made with high-quality raw materials, a porous metal shell, and excellent heat dissipation performance, the adapters are strong and suitable for indoor use. With automatic overload cut-off, over Voltage cut-off, automatic thermal cut-off, and short circuit protection, your electronic products are safe from destruction. Suitable for various 5V projects, such as WS2811 WS 2801 WS2812B SK6812 SK9822 APA102 LED Strip Pixel Light, CCTV Camera, Security System, Computer Project, etc.',
  'image': 'https://m.media-amazon.com/images/I/41xpAE9UyQL._AC_.jpg',
  'rating_number': 50,
  'price': 14.99,
  'average_rating': 4.6,
  'parent_asin': 'B0CGFTRWX6'},
 {'description': 'Best360 Monopod Pro Carbon Fiber Edition 2 In 1 360 Camera Stand And Phone Stand PEACE OF MIND: Reduce the risk of your 360 camera or phone getting blown over by the wind or getting knocked over too easily. MULTI PURPOSE: Perfect for virtual tours, travelling, vr filmmaking, documentaries, journalism, and vlogging. MODULAR: The Selfie Stick, Counterweight, and Tripod Legs can be separated to pack into a small travel backpack. STURDY: The extra long Tripod Legs and hefty 500g Counterweight keeps the monopod standing upright in light wind. EXTRA STABILITY: Extend each Tripod Leg from 20cm to 32cm for a wider and more stable base.',
  'image': 'https://m.media-amazon.com/images/I/211rb7PVVAL._AC_.jpg',
  'rating_number': 14,
  'price': nan,
  'average_rating': 4.0,
  'parent_asin': 'B0B8WDV287'},
 {'description': "TESmart 8x8 HDMI Matrix 4K Matrix Switcher Support EDID, 4K@30HZ, 1080P 3D, HDCP, 8 in 8 Out HDMI Switch with IR Remote Control, RS232, TCP/IP Control, Rack-Mount HDMI Matrix 【8 in 8 out HDMI Matrix】It allows 8 HDMI source devices to cross-connect to 8 HDMI displays at the same time.You can use it as HDMI Splitter as well as HDMI Switch,becase each display can share the same input or select differient inputs.Features an LCD screen on the front panel to show you the real-time connection status. 【4k image and a Wide Range of Audio Formats】Support superior video quality up to 3840x2160@30Hz (including 1080p 3D video). It's HDCP compliant.This 4k matrix supports PCM, Dolby AC3 and DSD audio format.Common scenarios include: classrooms, auditoriums, department stores, Commercial and residential AV systems, etc. 【Smart EDID Management】With EDID management, the HDMI source player will output the best possible resolution to ensure the compatibility of all HDMI displays. 【4 control methods 】Support multiple control methods for system management including front buttons, IR remote control, RS-232 control and LAN commands.(You can turn off the beep by sending TCP/IP commands). 【Preset function】You can keep the usaully used connection status to 1-4,then recall it quikly as your requirement.(Please refer to the manual for details). 【Power Off Memory Function】It can automatically restore the previous matrix status the next time the power is turned on. 【1 year warranty】We offer you 1 year warranty from the date of order. And we offer free Tech Support.If you have any problems, please free to to let us know . TESmart is strive to offer you a satisfying After-Sales Service.",
  'image': 'https://m.media-amazon.com/images/I/31PZRMd-fyL._AC_.jpg',
  'rating_number': 30,
  'price': 675.25,
  'average_rating': 3.7,
  'parent_asin': 'B07YD9N85J'},
 {'description': 'New Lenovo 230w ac Adapter Compatible with Lenovo Legion 5 Charger for Lenovo Legion 5 7 5P C7 S7 Y540 Y545 Y740 Y730 Y900 Y910 Y920 Y7000 4X20E75111 GX20L29347 ADL230NDC3A ADL230NLC3A 💯Output: 20V 11.5A 230W Input:100V-240V 50-60Hz 💯Compatible With Lenovo T431s,T440,T440p,T440s,T450,T450s,T460,T460p,T460s,T470,T470p,T540p,T550,T560,T570,TP25.a.W550s, X1 Carbon (2nd Gen), X1 Carbon (3rd Gen) , X1 Carbon (4th Gen) , X1 Yoga (1st Gen) , X240,X240s ,X250,X260,P40 ,Yoga P50,P50s,P51,P51s,P70,P71.E440,E450,E455,E460,E465,E470,E475,E540,E550,E550c,E555,E560,E560p,E565,E570,E570p,E575,S1 Yoga 12, S3 Yoga 14,S5 Yoga 15,Yoga 14,Yoga 260,Yoga 460,L440,L450,L460,L540,L560,L570. 💯Compatible with Lenovo Ideapad Legion Y920 Y910 Y900 Y740 Y730 Y7000 Y545 Y540 5 5P C7 5-15ARH05H 5-15IMH05H 5-17IMH05H 5-17ARH05H 5P-15IMH05 5P-15IMH05H 5P-15ARH05H 7-15IMH05 7-15IMHg05 C7-15IMH05 81HE 81HH 81RJ 81SX 81SY 81Q6 81T2 Laptop 💯The 230W Charger provides strong protection against overheating, overcurrent, short circuit, overvoltage and overcharge.BULL-TECH 230W Charger has been tested, approved, and certified by Underwriter Laboratories. 💯Warranty: This product is eligible for replacement or refund within 30 days,and the manufacturer provides an additional 12 Months Warranty.',
  'image': 'https://m.media-amazon.com/images/I/31O5105XuGL._AC_.jpg',
  'rating_number': 10,
  'price': nan,
  'average_rating': 2.8,
  'parent_asin': 'B0BDRGBRN5'},
 {'description': 'Intel Core i7-9700K Desktop Processor & MSI Z390-A PRO LGA1151 (Intel 8th and 9th Gen) M.2 USB 3.1 Gen 2 DDR4 HDMI DP CFX Dual Gigabit LAN ATX Z390 Gaming Motherboard ',
  'image': 'https://m.media-amazon.com/images/I/41i6RHrHrGL._AC_.jpg',
  'rating_number': 29,
  'price': nan,
  'average_rating': 4.9,
  'parent_asin': 'B08P65FZCZ'},
 {'description': 'Bauhoo Charging Station for Apple Multiple Devices, 3 in 1 Fast Wireless Charger Foldable iPhone 14/13/12/11/Pro/XS/Xs Max/XR/X/SE/8/8 Plus Watch 8/7/6/SE/5/4/3/2 AirPods 3/2/Pro with Adapter Pink 0',
  'image': 'https://m.media-amazon.com/images/I/41iK0-+HVSL._AC_.jpg',
  'rating_number': 159,
  'price': 17.75,
  'average_rating': 4.1,
  'parent_asin': 'B0BHRHS1Q7'},
 {'description': 'SXCY 2022 2023 Chevy Silverado 1500 Tempered Glass Screen Protector 13.4 Inch for 2023 2022 Chevy Silverado 1500 13.4 Inch Touch Screen Clear Tempered Glass Film 2023 Chevy Silverado 1500 Touch Accurate Navigation Screen Panel Screen Protector for 2023 Chevy Silverado 1500 LT/RST/LT Trail Boss/LTZ/ZR2/High Country Precisely Measured and Laser Cut: It is exclusive designed for 2022 2023 Chevy Silverado 1500 13.4 Inch Touch Screen LT/RST/LT Trail Boss/LTZ/ZR2/High Country Touch Screen and compatible with your vehicle Keep the screen clear and dust-free: protects your 2022 2023 Chevy Silverado 1500 13.4 Inch screen from daily scratches, dust and scrapes Great protection: SXCY 2022 2023 Chevy Silverado 1500 13.4 Inch film is using tough glass material, this high definition transparency film can ensure maximum resolution and provide your touch Screen a great protection Touch Sensitivity: it will not affect the clarity of the 2022 2023 Chevy Silverado 1500 13.4 Inch navigator. It protects the screen while keeping the touch sensitive Easy to stall: it is a great tempered glass film, with light and thin material , and the difficulty of sticking is small !!!Please be sure that the film is suitable for your 2022 2023 Chevy Silverado 1500 13.4 Inch screen before placing an order',
  'image': 'https://m.media-amazon.com/images/I/41nN9KCiwwL._AC_.jpg',
  'rating_number': 52,
  'price': 20.13,
  'average_rating': 4.3,
  'parent_asin': 'B0BCV4B69Z'},
 {'description': 'Jicjocy Wireless Earbuds Bluetooth Active Noise Cancelling Earbuds, Hi-Fi Stereo Bluetooth Headphones with Charging Case, Waterproof in-Ear Earphones with Mic for iPhone/Android ♫【ANC Bluetooth Headphones】Bluetooth wireless earbuds have "Active Noise Cancellation" technology, which can cancel up to 40dB of noise, and ANC mode allows you to enjoy clear calls. You can also switch to Transparency mode at any time to hear your surroundings without removing the earbuds. ♫【Hi-Fi Stereo Sound】Bluetooth earbuds have built-in 13mm drivers and three-layer composite diaphragm provide deep bass, stunning highs and clear mids. Hi fi stereo sound earbuds are suitable for listening to music, making phone calls, watching videos and playing games. The natural and authentic sound for immersive music enjoyment. It can support the mono mode and twin stereo mode, you can share the earbuds with your friends and families. ♫【Auto Pairing, Smart Touch Control】Take out the two earbuds from the charging case, just enable the bluetooth connection on your phone and they will pair automatically. During use, you can control the phone by touching the earbuds, such as answering calls, switching music, activating the voice assistant, switching ANC/transparency mode, etc. Compared with traditional physical buttons, touch control is more convenient and simple. ♫【Waterproof & Charge Anytime】Jicjocy wireless headphones are coated with IPX8 nano-waterproof coating, which can effectively resist rain and sweat. Enjoy sports and outdoor activities without worrying about getting wet or sweating. 1.5 Hrs charging, the earbuds can listen to music for 6-8 hours and talk for 4 hours on a single charge. charging case can provide 4 times full charging for both earbuds, so you can enjoy 40H music time in total via using in turn. ♫【Comfortable Fit & Warranty】Our wireless bluetooth earphones feature a new ergonomic "in-ear" design with 3 pairs of ear tips in different sizes to ensure a comfortable fit and long-lasting wear. So that you don\'t have to worry about earbuds falling off when running, exercising, exercising, and driving. Ultralight and small wireless earbuds for kids and adults, while exquisite earbuds make a great choice for Christmas gifts. We value every customer\'s shopping experience. We offer a 90-day replacement and warranty. If you have any questions or need any help, please feel free to contact us.',
  'image': 'https://m.media-amazon.com/images/I/41n+OhhiJrL._AC_.jpg',
  'rating_number': 171,
  'price': 14.99,
  'average_rating': 4.2,
  'parent_asin': 'B0C61MMPVB'},
 {'description': "YYJOY Spy Camera Hidden Camera Wireless Small Camera Nanny Cam,Wi-Fi,Night Vision,4K HD Mini Security Camera Indoor,Phone APP, Motion Detection,Battery Powered Spy Cam for Home,Easy to Use 𝐂𝐨𝐦𝐩𝐚𝐜𝐭 𝐚𝐧𝐝 𝐄𝐚𝐬𝐲 𝐭𝐨 𝐜𝐨𝐧𝐧𝐞𝐜𝐭: This camera is easy to install with magnetic base. The wifi connection is optimized for faster and more convenient scanning, and the app supports up to 4 cameras, making it perfect for home security or monitoring. 𝐖𝐢𝐫𝐞𝐥𝐞𝐬𝐬 𝐋𝐨𝐧𝐠-𝐥𝐚𝐬𝐭𝐢𝐧𝐠 𝐁𝐚𝐭𝐭𝐞𝐫𝐲 𝐋𝐢𝐟𝐞: Equipped with a 1200 mAh rechargeable battery, this wireless indoor camera can record continuously for 4 hours. You can also use the usb cable to powered by a power bank to seize the moment. 𝟒𝐊 𝐔𝐥𝐭𝐫𝐚 𝐇𝐃 𝐋𝐢𝐯𝐞 𝐕𝐢𝐝𝐞𝐨 & 𝐍𝐢𝐠𝐡𝐭 𝐕𝐢𝐬𝐢𝐨𝐧: Featuring a 160° wide-angle lens, this wireless security camera captures details with stunning 4K resolution. Night vision mode allows the camera to capture subjects up to 26 feet away in low light conditions. Also , this wireless camera is magnetic, easy to install in many places. 𝐒𝐦𝐚𝐫𝐭 𝐀𝐈 𝐇𝐮𝐦𝐚𝐧 𝐒𝐡𝐚𝐩𝐞 𝐒𝐞𝐧𝐬𝐨𝐫: Our nanny camera uses a high-sensitivity PIR sensor that can differentiate people from other moving objects, avoiding false alarms and saving you time and worry. Colors are reflected accurately in either stronger or weaker lighting. 𝐋𝐨𝐨𝐩 𝐑𝐞𝐜𝐨𝐫𝐝𝐢𝐧𝐠 𝐚𝐧𝐝 𝐌𝐮𝐥𝐭𝐢-𝐔𝐬𝐞: Record video onto a Micro SD card (not included) . With multi-protection and surge protection, this indoor security camera can be placed in children's rooms, kitchens, offices, car or backyard or even mounted on a drone for recording.",
  'image': 'https://m.media-amazon.com/images/I/41F4u2dntKL._AC_.jpg',
  'rating_number': 44,
  'price': nan,
  'average_rating': 3.9,
  'parent_asin': 'B0C4P45FXV'},
 {'description': "Compressed Air Duster 6000mAh Battery - Electric Air Duster Addcolor AD-38 Keyboard Cleaner for Office-3 Adjustable Wind Speeds with LED Light, Cordless & Reusable Canned Air Duster for Computers 【⚡Air Duster with High Applicability】This compressed air duster can be widely used in your living room or bedroom/office/studio/car. You can use it when you want to clean the air conditioner, blinds and other corners that are hard to clean everyday; dust in your computer is not so easy to see, so you can use it to clean dust for your case and make sure your computer fan can work properly!! 【⚡One Air Duster for Multiple Uses】An electric air duster can contain multiple functions and achieve different results with the 5 accessories included. In addition to the nozzles with brushes for keyboard clean, you can also use the small inflatable nozzles to pump up the kids' swimming laps and the long nozzles to speed up the charcoal burning for family gatherings at the yard barbecue! ! Two nozzles at different heights can be used to quickly exhaust gas, for example for your airbed. 【⚡Great Replacement to Air Can Dusters】Compared to traditional disposable air canisters, the electronic duster offers 3 adjustable wind speeds: Gear 1-3: This means 51,000-100000 rotations per minute with (Max)50-25(Min) minutes of endurance; also, since it is rechargeable, it avoids environmental pollution from discarded canisters and more importantly saves the cost of buying air canisters time and time again.It is the great replacement to Air Can Dusters. 【⚡LED Lighting Design, Fast Charging】This air duster has a front LED light that provides good illumination when you need to clean a dark corner. The compressed air duster does not produce any liquid during use, so you can clean electronics such as keyboards or computer mainframes with confidence. Compared to most similar duster, we have added a fast charging feature, which means you only need to spend 2 hours to be fully charged quickly. 【⚡Cordless Design, Easy to Use】This AD-38 Electric Air Duster allows you to easily remove dust from the surface of objects，small size and lightweight（800g）, even ladies can hold it for long periods of time, this way you can easily clean your air conditioner or blinds more deeply, ensuring that it can be used around the house.Thanks to the built-in battery, no need to plug in, safety, efficient and convenient. It is equipped with a free storage bag that will not disrupt the order of your room. 【💖Tips for Use】: Before charging for the first time, you need to completely use off the power of the product (this will help the battery memory)",
  'image': 'https://m.media-amazon.com/images/I/41PJXJasmFL._AC_.jpg',
  'rating_number': 17,

###Embedding function definition

In [16]:
response = openai.embeddings.create(
    input="Random text",
    model="text-embedding-3-small",
)

In [17]:
len(response.data[0].embedding)

1536

In [18]:
def get_embedding(text,model="text-embedding-3-small"):
    response = openai.embeddings.create(
        input=text,
        model=model,
    )
    return response.data[0].embedding

In [19]:
get_embedding("Hi")

[-0.006954193115234375,
 -0.03533935546875,
 0.0015869140625,
 0.06536865234375,
 0.032928466796875,
 -0.0242156982421875,
 -0.026123046875,
 0.049407958984375,
 0.0162506103515625,
 -0.05169677734375,
 -0.01343536376953125,
 -0.0144805908203125,
 -0.0260009765625,
 -0.0032596588134765625,
 0.02459716796875,
 0.0011425018310546875,
 -0.053497314453125,
 0.01508331298828125,
 0.01148223876953125,
 0.033935546875,
 0.049285888671875,
 0.020355224609375,
 -0.01395416259765625,
 0.01885986328125,
 0.0171661376953125,
 0.0241851806640625,
 0.0182647705078125,
 -0.0012063980102539062,
 0.0196075439453125,
 -0.03680419921875,
 0.027679443359375,
 -0.0282440185546875,
 0.0276641845703125,
 -0.0162200927734375,
 -0.0117645263671875,
 -0.016021728515625,
 -0.0140838623046875,
 0.037567138671875,
 0.0189208984375,
 -0.03765869140625,
 0.04345703125,
 -0.012420654296875,
 0.0209503173828125,
 0.0135040283203125,
 0.0019893646240234375,
 0.00025463104248046875,
 -0.04913330078125,
 0.00832366943359375,
 0.0183868408203125,
 0.0294647216796875,
 -0.0267486572265625,
 0.00762176513671875,
 0.024993896484375,
 0.10650634765625,
 0.036285400390625,
 -0.010284423828125,
 0.059539794921875,
 0.023651123046875,
 -0.004093170166015625,
 0.00013363361358642578,
 -0.0191192626953125,
 0.00971221923828125,
 0.00835418701171875,
 0.004024505615234375,
 -0.007110595703125,
 -0.0135650634765625,
 -0.02392578125,
 0.01214599609375,
 -0.0209503173828125,
 -0.0138702392578125,
 -0.00142669677734375,
 0.0362548828125,
 -0.0286102294921875,
 -0.007221221923828125,
 -0.004337310791015625,
 -0.030120849609375,
 -0.08526611328125,
 -0.037750244140625,
 -0.0012693405151367188,
 0.0097503662109375,
 -0.0274505615234375,
 0.0221405029296875,
 -0.037109375,
 -0.01194000244140625,
 -0.0562744140625,
 -0.006053924560546875,
 -0.08074951171875,
 0.0163726806640625,
 -0.026702880859375,
 -0.00923919677734375,
 -0.01568603515625,
 0.044219970703125,
 -0.028411865234375,
 -0.0235443115234375,
 0.00933837890625,
 0.01165008544921875,
 -0.024749755859375,
 -0.0011453628540039062,
 0.05902099609375,
 -0.00936126708984375,
 0.037872314453125,
 -0.0294036865234375,
 0.0396728515625,
 -0.0104827880859375,
 0.01157379150390625,
 0.039306640625,
 0.00847625732421875,
 -0.011260986328125,
 -0.053131103515625,
 0.0255889892578125,
 -0.06597900390625,
 -0.07818603515625,
 -0.0011310577392578125,
 0.01006317138671875,
 0.00897979736328125,
 0.040496826171875,
 0.01519775390625,
 -0.057342529296875,
 -0.00016546249389648438,
 -0.06658935546875,
 0.00370025634765625,
 -0.0048828125,
 0.0283203125,
 -0.036529541015625,
 -0.06097412109375,
 0.0211334228515625,
 0.0011720657348632812,
 0.0168609619140625,
 -0.04742431640625,
 0.0035858154296875,
 0.0506591796875,
 0.01546478271484375,
 -0.0258026123046875,
 -0.007259368896484375,
 -0.029876708984375,
 0.03668212890625,
 -0.037445068359375,
 0.028289794921875,
 -0.043792724609375,
 -0.0225372314453125,
 0.031219482421875,
 -0.00887298583984375,
 0.005741119384765625,
 -0.0159912109375,
 0.0219879150390625,
 -0.01502227783203125,
 0.001239776611328125,
 0.0670166015625,
 -0.0281219482421875,
 -0.01538848876953125,
 0.027099609375,
 0.0218048095703125,
 -0.05230712890625,
 0.024444580078125,
 0.01270294189453125,
 -0.029510498046875,
 0.0150299072265625,
 -0.029510498046875,
 -0.0239105224609375,
 0.008544921875,
 0.033294677734375,
 0.0160980224609375,
 0.01226806640625,
 -0.0526123046875,
 -0.038970947265625,
 0.01161956787109375,
 0.028350830078125,
 0.0367431640625,
 -0.032806396484375,
 -0.0012140274047851562,
 -0.024871826171875,
 0.0292816162109375,
 -0.0323486328125,
 -0.0079345703125,
 -0.01256561279296875,
 -0.005157470703125,
 0.0093231201171875,
 0.0001804828643798828,
 -0.06842041015625,
 -0.0179901123046875,
 0.0164337158203125,
 0.09735107421875,
 0.0054168701171875,
 0.005706787109375,
 -0.032745361328125,
 -0.0205230712890625,
 -0.01186370849609375,
 0.005298614501953125,
 0.02130126953125,
 0.043304443359375,
 0.0006113052368164062,
 0.061859130859375,
 0.00408172607421875,
 0.0051727294921875,
 -0.0060882568359375,
 -0.0443115234375,
 0.0809326171875,
 -0.007312774658203125,
 -0.005275726318359375,
 -0.0023632049560546875,
 0.0218505859375,
 -0.05535888671875,
 0.0171356201171875,
 -0.01450347900390625,
 -0.0244903564453125,
 -0.0212249755859375,
 0.0222930908203125,
 0.0579833984375,
 -0.00018334388732910156,
 -0.048187255859375,
 0.05255126953125,
 -0.033843994140625,
 0.00704193115234375,
 0.0300750732421875,
 -0.01337432861328125,
 -0.034698486328125,
 0.044952392578125,
 0.0028324127197265625,
 0.050018310546875,
 0.01233673095703125,
 -0.00939178466796875,
 0.0027828216552734375,
 0.062255859375,
 0.034210205078125,
 0.021820068359375,
 0.0178375244140625,
 -0.01308441162109375,
 -0.01313018798828125,
 0.01541900634765625,
 -0.0341796875,
 0.0223541259765625,
 0.049224853515625,
 -0.0477294921875,
 -0.046661376953125,
 0.0200042724609375,
 0.0228271484375,
 0.03033447265625,
 -0.01256561279296875,
 0.0163726806640625,
 -0.0150299072265625,
 -0.0338134765625,
 0.006473541259765625,
 0.0006685256958007812,
 0.027740478515625,
 0.022125244140625,
 -0.0040130615234375,
 0.00859832763671875,
 -0.0650634765625,
 0.01325225830078125,
 0.01546478271484375,
 0.008575439453125,
 0.01056671142578125,
 0.01342010498046875,
 -0.0222015380859375,
 -0.027557373046875,
 0.0258636474609375,
 0.0035915374755859375,
 0.038665771484375,
 -0.024810791015625,
 -0.04058837890625,
 -0.0237274169921875,
 -0.037261962890625,
 -0.00653839111328125,
 -0.044464111328125,
 -0.055908203125,
 -0.04241943359375,
 0.01171112060546875,
 0.031219482421875,
 -0.01395416259765625,
 0.005786895751953125,
 -0.0034809112548828125,
 -0.02642822265625,
 0.035369873046875,
 -0.01007080078125,
 -0.0068511962890625,
 0.0150299072265625,
 0.0205230712890625,
 -0.016510009765625,
 -0.0003383159637451172,
 0.0164337158203125,
 -0.046630859375,
 -0.023651123046875,
 -0.006351470947265625,
 0.035491943359375,
 -0.06854248046875,
 0.0202484130859375,
 -0.00971221923828125,
 -0.034576416015625,
 0.03424072265625,
 0.029541015625,
 0.035888671875,
 0.01049041748046875,
 -0.01104736328125,
 -0.033447265625,
 0.003017425537109375,
 0.0179595947265625,
 -0.0066070556640625,
 -0.0220947265625,
 0.0236968994140625,
 -0.03240966796875,
 0.0714111328125,
 0.0149078369140625,
 0.0093841552734375,
 -0.0008640289306640625,
 -0.008331298828125,
 0.0288238525390625,
 0.00365447998046875,
 -0.03118896484375,
 0.00817108154296875,
 0.0066986083984375,
 -0.035186767578125,
 0.0140838623046875,
 0.03472900390625,
 -0.0280914306640625,
 -0.041015625,
 0.0034160614013671875,
 -0.00045180320739746094,
 -0.01464080810546875,
 0.00241851806640625,
 -0.04412841796875,
 0.006450653076171875,
 -0.04644775390625,
 0.027557373046875,
 -0.01715087890625,
 0.0007128715515136719,
 -0.0209808349609375,
 0.0609130859375,
 0.00864410400390625,
 -0.01812744140625,
 -0.0114898681640625,
 -0.0009918212890625,
 -0.023651123046875,
 0.0037441253662109375,
 -0.007396697998046875,
 0.0191802978515625,
 0.00792694091796875,
 -0.0430908203125,
 0.0235748291015625,
 -0.052215576171875,
 0.0509033203125,
 -0.0247955322265625,
 -0.050048828125,
 -0.058319091796875,
 0.01065826416015625,
 0.006870269775390625,
 -0.0106658935546875,
 0.00433349609375,
 -0.0106201171875,
 -0.0173492431640625,
 -0.0088043212890625,
 0.036590576171875,
 0.036956787109375,
 -0.0159912109375,
 -0.02587890625,
 -0.02069091796875,
 -0.03619384765625,
 0.071044921875,
 -0.002899169921875,
 -0.01165771484375,
 0.05010986328125,
 -0.056549072265625,
 0.0002474784851074219,
 0.0009765625,
 -0.03662109375,
 0.053558349609375,
 0.032073974609375,
 -0.06048583984375,
 0.004283905029296875,
 0.0207366943359375,
 0.051025390625,
 -0.01318359375,
 0.01358795166015625,
 0.0013637542724609375,
 0.0117950439453125,
 -0.04095458984375,
 0.0231170654296875,
 0.03863525390625,
 -0.00536346435546875,
 0.01149749755859375,
 -0.0015935897827148438,
 0.0195159912109375,
 0.0506591796875,
 0.0175628662109375,
 -0.028564453125,
 0.05731201171875,
 -0.007396697998046875,
 0.025054931640625,
 -0.038787841796875,
 -0.0308990478515625,
 0.015869140625,
 0.07806396484375,
 0.0032253265380859375,
 0.042449951171875,
 -0.0235595703125,
 0.01837158203125,
 -0.0203399658203125,
 0.036102294921875,
 0.0227203369140625,
 -0.00960540771484375,
 -0.01220703125,
 0.02191162109375,
 -0.060302734375,
 0.0103912353515625,
 0.0091705322265625,
 -0.01244354248046875,
 -0.0193328857421875,
 -0.04937744140625,
 0.01158905029296875,
 0.020263671875,
 -0.016021728515625,
 0.0155029296875,
 -0.04864501953125,
 0.056976318359375,
 0.022705078125,
 0.02703857421875,
 -0.028289794921875,
 -0.0132293701171875,
 -0.00849151611328125,
 0.0151214599609375,
 0.0095672607421875,
 0.01218414306640625,
 0.00016498565673828125,
 -0.0198211669921875,
 0.0255584716796875,
 -0.01727294921875,
 0.046478271484375,
 0.04315185546875,
 -0.06390380859375,
 0.01387786865234375,
 -0.07275390625,
 -0.0229949951171875,
 0.011260986328125,
 -0.01212310791015625,
 0.040496826171875,
 -0.040374755859375,
 -0.0128326416015625,
 0.006866455078125,
 0.038726806640625,
 0.0238189697265625,
 0.0236358642578125,
 -0.00591278076171875,
 -0.0078277587890625,
 -0.00844573974609375,
 -0.03973388671875,
 -0.01006317138671875,
 -0.044219970703125,
 -0.003932952880859375,
 -0.00711822509765625,
 -0.022857666015625,
 -0.0186614990234375,
 -0.0148773193359375,
 -0.002674102783203125,
 0.0080108642578125,
 0.00360107421875,
 0.006786346435546875,
 0.02197265625,
 0.01087188720703125,
 -0.009979248046875,
 0.0027313232421875,
 -0.029388427734375,
 0.0247344970703125,
 -0.0003249645233154297,
 0.04766845703125,
 0.0355224609375,
 0.0236053466796875,
 -0.034759521484375,
 0.0022106170654296875,
 -0.007663726806640625,
 -0.0221710205078125,
 -0.0758056640625,
 0.0294342041015625,
 0.0118560791015625,
 0.04754638671875,
 -0.00933074951171875,
 -0.01491546630859375,
 -0.039947509765625,
 0.002056121826171875,
 -0.01995849609375,
 0.006038665771484375,
 -0.015167236328125,
 0.004207611083984375,
 -0.006122589111328125,
 -0.034271240234375,
 0.066162109375,
 -0.01026153564453125,
 0.0723876953125,
 0.0244293212890625,
 0.02105712890625,
 -0.044036865234375,
 -0.035003662109375,
 0.0196685791015625,
 0.01983642578125,
 0.0870361328125,
 -0.0184173583984375,
 -0.0291290283203125,
 -0.0157623291015625,
 0.0019683837890625,
 -0.0030689239501953125,
 -0.04052734375,
 -0.051422119140625,
 -0.01534271240234375,
 0.00829315185546875,
 -0.0081787109375,
 0.051727294921875,
 0.04180908203125,
 -0.038848876953125,
 -0.032501220703125,
 0.01256561279296875,
 -0.01227569580078125,
 -0.0150146484375,
 0.0067901611328125,
 0.04522705078125,
 -0.01256561279296875,
 -0.056427001953125,
 -0.024688720703125,
 -0.0036067962646484375,
 -0.001644134521484375,
 -0.006252288818359375,
 0.02447509765625,
 -0.034149169921875,
 0.025634765625,
 0.00678253173828125,
 -0.025421142578125,
 -0.006855010986328125,
 0.005031585693359375,
 -0.016448974609375,
 -0.011474609375,
 -0.031280517578125,
 -0.005279541015625,
 0.00202178955078125,
 0.038848876953125,
 -0.017425537109375,
 -0.032470703125,
 0.0056915283203125,
 -0.0287322998046875,
 0.00962066650390625,
 -0.005336761474609375,
 -0.044403076171875,
 0.0004024505615234375,
 -0.02874755859375,
 0.03436279296875,
 0.006206512451171875,
 0.01303863525390625,
 0.0117034912109375,
 -0.0020599365234375,
 0.0249176025390625,
 0.0330810546875,
 -0.00566864013671875,
 0.041351318359375,
 0.041839599609375,
 -0.0196990966796875,
 -0.0309600830078125,
 0.044403076171875,
 -0.01018524169921875,
 0.02099609375,
 -0.0184783935546875,
 -0.0252227783203125,
 -0.004535675048828125,
 0.0099334716796875,
 0.0195159912109375,
 0.004276275634765625,
 -0.00250244140625,
 0.01358795166015625,
 0.007259368896484375,
 0.0006437301635742188,
 0.03411865234375,
 -0.009368896484375,
 -0.0281982421875,
 0.005802154541015625,
 -0.02349853515625,
 -0.0161895751953125,
 -0.0087738037109375,
 -0.0289154052734375,
 -0.011444091796875,
 0.0086212158203125,
 -0.0152587890625,
 -0.0034809112548828125,
 0.0103759765625,
 0.035552978515625,
 0.009765625,
 -0.024383544921875,
 -0.02239990234375,
 -0.00887298583984375,
 -0.033172607421875,
 -0.0235748291015625,
 0.0013675689697265625,
 -0.0107421875,
 0.0280303955078125,
 0.029571533203125,
 0.0305633544921875,
 0.0169219970703125,
 -2.562999725341797e-05,
 -0.0017423629760742188,
 0.027252197265625,
 0.01158905029296875,
 -0.004146575927734375,
 -0.0214080810546875,
 -0.045745849609375,
 -0.03424072265625,
 0.004215240478515625,
 0.0018758773803710938,
 -0.01544952392578125,
 -0.0013532638549804688,
 -0.06658935546875,
 0.01267242431640625,
 -0.0037403106689453125,
 0.0025806427001953125,
 0.0223541259765625,
 -0.016876220703125,
 -0.023895263671875,
 -0.0008182525634765625,
 0.0408935546875,
 0.011505126953125,
 -0.041290283203125,
 -0.033050537109375,
 0.02301025390625,
 -0.001796722412109375,
 0.02685546875,
 0.016326904296875,
 -0.0128326416015625,
 -0.01544952392578125,
 -0.0355224609375,
 0.007312774658203125,
 0.03778076171875,
 0.039642333984375,
 0.0211944580078125,
 -0.0230712890625,
 -0.026092529296875,
 -0.035003662109375,
 0.002056121826171875,
 0.01983642578125,
 0.0243988037109375,
 0.023956298828125,
 -0.013671875,
 -0.0272369384765625,
 -0.0032806396484375,
 -0.006744384765625,
 -0.0101776123046875,
 0.016082763671875,
 -0.039306640625,
 0.01056671142578125,
 -0.003307342529296875,
 0.0163421630859375,
 -0.0008912086486816406,
 0.03411865234375,
 -0.00025534629821777344,
 0.005283355712890625,
 0.01441192626953125,
 0.01116180419921875,
 -0.0189361572265625,
 0.0025424957275390625,
 -0.044403076171875,
 -0.00469970703125,
 -0.016143798828125,
 -0.0034198760986328125,
 -0.003108978271484375,
 -0.040252685546875,
 -0.006084442138671875,
 -0.01239013671875,
 0.00566864013671875,
 0.0095672607421875,
 -0.0092315673828125,
 -0.0173492431640625,
 -0.0187835693359375,
 -0.01100921630859375,
 0.00913238525390625,
 0.0131072998046875,
 0.00479888916015625,
 -0.01494598388671875,
 -0.021087646484375,
 0.01349639892578125,
 0.0021820068359375,
 0.03692626953125,
 -0.0284881591796875,
 0.047821044921875,
 0.005207061767578125,
 0.039886474609375,
 -0.050689697265625,
 -0.0193939208984375,
 -0.034423828125,
 -0.0167236328125,
 0.005115509033203125,
 -0.0177154541015625,
 -0.01678466796875,
 0.00020313262939453125,
 0.030303955078125,
 0.03143310546875,
 -0.009246826171875,
 0.0036449432373046875,
 0.0282745361328125,
 0.00029468536376953125,
 0.009521484375,
 0.029693603515625,
 -0.0189971923828125,
 0.003177642822265625,
 -0.03704833984375,
 0.0457763671875,
 -0.0253143310546875,
 0.024932861328125,
 -0.07769775390625,
 0.0022125244140625,
 -0.028076171875,
 -0.0163421630859375,
 0.0019855499267578125,
 -0.0023403167724609375,
 0.00598907470703125,
 -0.0297088623046875,
 0.0180816650390625,
 -0.0025081634521484375,
 0.025787353515625,
 -0.0241241455078125,
 0.0166473388671875,
 -0.01776123046875,
 -0.00836944580078125,
 0.045379638671875,
 0.024566650390625,
 -0.01372528076171875,
 -0.02947998046875,
 0.02264404296875,
 -0.021820068359375,
 -0.01055145263671875,
 -0.02398681640625,
 -0.023101806640625,
 -0.014434814453125,
 0.0189208984375,
 -0.03106689453125,
 -0.03826904296875,
 0.012054443359375,
 0.054107666015625,
 0.0124664306640625,
 -0.012847900390625,
 0.0089263916015625,
 0.013275146484375,
 0.027862548828125,
 0.034454345703125,
 0.0023441314697265625,
 -0.031402587890625,
 -0.038787841796875,
 -0.020599365234375,
 -0.059814453125,
 -0.00122833251953125,
 0.01198577880859375,
 0.020416259765625,
 -0.00429534912109375,
 0.0143280029296875,
 -0.0239105224609375,
 0.041656494140625,
 0.041534423828125,
 -0.024017333984375,
 -0.006229400634765625,
 0.0191192626953125,
 0.0121002197265625,
 -0.0221710205078125,
 0.01241302490234375,
 0.0091094970703125,
 -0.0271148681640625,
 0.03753662109375,
 -0.018310546875,
 0.043487548828125,
 0.0182647705078125,
 0.0228271484375,
 0.035919189453125,
 -0.01290130615234375,
 -0.0168609619140625,
 -0.0300445556640625,
 -0.0119781494140625,
 -0.03643798828125,
 -0.0188751220703125,
 -0.038299560546875,
 -0.01287841796875,
 0.018218994140625,
 -0.0198211669921875,
 -0.0010347366333007812,
 0.00390625,
 0.0168304443359375,
 -0.016082763671875,
 -0.00778961181640625,
 -0.01291656494140625,
 -0.03570556640625,
 0.019287109375,
 0.00493621826171875,
 0.0263519287109375,
 0.033660888671875,
 -0.00026869773864746094,
 -0.020751953125,
 -0.04705810546875,
 -0.00864410400390625,
 0.0019550323486328125,
 -0.0029811859130859375,
 -0.00799560546875,
 -0.00562286376953125,
 -0.035736083984375,
 0.0266876220703125,
 -0.0280914306640625,
 0.007450103759765625,
 0.024810791015625,
 0.010345458984375,
 -0.019866943359375,
 0.0202178955078125,
 0.0033283233642578125,
 -0.00937652587890625,
 -0.02117919921875,
 0.0206756591796875,
 0.0180511474609375,
 -0.004024505615234375,
 -0.002483367919921875,
 -0.028839111328125,
 -0.008453369140625,
 -0.00646209716796875,
 -0.008270263671875,
 -0.01313018798828125,
 -0.005985260009765625,
 -0.01053619384765625,
 0.007671356201171875,
 0.0021610260009765625,
 -0.01093292236328125,
 0.01126861572265625,
 -0.043182373046875,
 0.013641357421875,
 0.022003173828125,
 0.04803466796875,
 0.048309326171875,
 -0.01541900634765625,
 -0.03680419921875,
 -0.0021686553955078125,
 0.0265350341796875,
 0.019775390625,
 0.0003764629364013672,
 0.014007568359375,
 -0.040771484375,
 0.01403045654296875,
 -0.03509521484375,
 -0.0129547119140625,
 -0.02618408203125,
 0.005138397216796875,
 0.05328369140625,
 0.0093536376953125,
 -0.01140594482421875,
 -0.015594482421875,
 -0.033538818359375,
 0.0225830078125,
 -0.0096435546875,
 0.0300750732421875,
 0.003520965576171875,
 0.0160675048828125,
 0.029815673828125,
 -0.00934600830078125,
 -0.01099395751953125,
 -0.01727294921875,
 7.534027099609375e-05,
 -0.01177215576171875,
 0.0072021484375,
 0.017791748046875,
 -0.02471923828125,
 0.0017385482788085938,
 -0.003772735595703125,
 -0.027862548828125,
 0.018280029296875,
 0.026031494140625,
 -0.01091766357421875,
 -0.040557861328125,
 0.037750244140625,
 0.0311279296875,
 9.292364120483398e-05,
 0.0037689208984375,
 -0.047119140625,
 0.021392822265625,
 -0.0165863037109375,
 0.025604248046875,
 0.023468017578125,
 0.0120697021484375,
 -0.0033779144287109375,
 -0.025787353515625,
 -0.044189453125,
 0.0267181396484375,
 0.041595458984375,
 0.0155792236328125,
 0.0161285400390625,
 -0.00882720947265625,
 -0.0034503936767578125,
 0.040679931640625,
 9.542703628540039e-05,
 -0.002109527587890625,
 -0.002567291259765625,
 0.0295257568359375,
 0.0016527175903320312,
 0.01132965087890625,
 0.0118865966796875,
 -0.0282135009765625,
 0.0289459228515625,
 0.0088958740234375,
 -0.040985107421875,
 0.01367950439453125,
 -0.035003662109375,
 -0.0079803466796875,
 0.0035572052001953125,
 -0.0215301513671875,
 0.00946807861328125,
 -0.014862060546875,
 -0.000545501708984375,
 -0.0266265869140625,
 -0.0309600830078125,
 -0.01531219482421875,
 -0.00565338134765625,
 0.0085906982421875,
 0.01140594482421875,
 0.0308074951171875,
 -0.0057525634765625,
 -0.001689910888671875,
 -0.036224365234375,
 -0.0036754608154296875,
 -0.029449462890625,
 0.0092620849609375,
 -0.012664794921875,
 -0.01386260986328125,
 0.01459503173828125,
 -0.0226898193359375,
 0.0088958740234375,
 0.01360321044921875,
 0.00092315673828125,
 0.001003265380859375,
 -0.01971435546875,
 -0.00428009033203125,
 0.0184783935546875,
 -0.038421630859375,
 -0.00946807861328125,
 -0.01175689697265625,
 0.0291900634765625,
 0.0078582763671875,
 0.031036376953125,
 -0.0238494873046875,
 0.006809234619140625,
 -0.00823211669921875,
 0.014862060546875,
 0.0255889892578125,
 0.0013179779052734375,
 0.0244598388671875,
 0.01702880859375,
 -0.0175933837890625,
 0.008056640625,
 -0.01183319091796875,
 -0.01702880859375,
 0.0274200439453125,
 0.0172271728515625,
 0.01934814453125,
 0.04791259765625,

### Quadrant Collection

In [20]:
qdrant_client=QdrantClient(url="http://localhost:6333")

In [22]:
qdrant_client.create_collection(
    collection_name="Amazon-items-collection-00",
    vectors_config=VectorParams(size=1536, distance=Distance.COSINE),
)

UnexpectedResponse: Unexpected Response: 409 (Conflict)
Raw response content:
b'{"status":{"error":"Wrong input: Collection `Amazon-items-collection-00` already exists!"},"time":0.719994993}'

### Embed Data

##### Test

In [23]:
pointstruct= PointStruct(
    id=0,
    vector=get_embedding("Test text"),
    payload={
        "text":"Test text",
        "model":"text-embedding-3-small",
    },
    )

In [24]:
pointstruct

PointStruct(id=0, vector=[-0.020111083984375, 0.0070037841796875, 0.0377197265625, -0.040252685546875, -0.0191802978515625, -0.0343017578125, 0.000576019287109375, -0.024261474609375, 0.038665771484375, 0.0015888214111328125, 0.0306243896484375, 0.01277923583984375, -0.01087188720703125, 0.011260986328125, 0.026397705078125, 0.04302978515625, -0.04681396484375, -0.006893157958984375, -0.021728515625, 0.05108642578125, 0.007061004638671875, 0.01308441162109375, 0.01129150390625, -0.032501220703125, -0.003940582275390625, -0.0390625, -0.03692626953125, 0.0050048828125, 0.058441162109375, -0.07452392578125, 0.0313720703125, -0.0440673828125, -0.0002703666687011719, -0.010955810546875, 0.00604248046875, 0.0382080078125, 0.0303192138671875, 0.03759765625, 0.0102386474609375, -0.02935791015625, -0.014923095703125, -0.01042938232421875, 0.021270751953125, 0.0181427001953125, 0.02667236328125, 0.00891876220703125, -0.01177978515625, 0.00879669189453125, 0.01995849609375, 0.037933349609375, -0.036346435546875, 0.0107269287109375, 0.0180816650390625, 0.0172576904296875, 0.02227783203125, -0.000576019287109375, -0.0469970703125, 0.040679931640625, -0.0034694671630859375, -0.0002868175506591797, 0.0244903564453125, 0.01541900634765625, 0.006580352783203125, 0.006916046142578125, -0.005435943603515625, -0.00359344482421875, 0.01142120361328125, 0.01161956787109375, -0.003459930419921875, -0.0031147003173828125, 0.0290374755859375, 0.01528167724609375, -0.05377197265625, 0.0015392303466796875, -0.048370361328125, -0.00786590576171875, -0.00406646728515625, 0.045654296875, -0.025726318359375, -0.0035991668701171875, 0.03271484375, 0.03033447265625, -0.01233673095703125, -0.02288818359375, -0.046417236328125, 0.0291900634765625, -0.126708984375, -0.00376129150390625, -0.00970458984375, -0.062744140625, -0.0059051513671875, -0.03240966796875, -0.0029582977294921875, -0.0094451904296875, 0.0396728515625, -0.033721923828125, -0.0116729736328125, -0.0022792816162109375, -0.0161895751953125, 0.004302978515625, 0.0273590087890625, 0.003025054931640625, -0.01158905029296875, 0.0202789306640625, 0.0077667236328125, 0.03936767578125, 0.01348114013671875, -0.0081634521484375, -0.032623291015625, 0.0171051025390625, -0.040863037109375, -0.020050048828125, 0.00019729137420654297, -0.0221710205078125, 0.0095977783203125, -0.01873779296875, 0.075927734375, -0.0804443359375, 0.00010496377944946289, -0.0545654296875, 0.0216217041015625, 0.00885772705078125, 0.023040771484375, -0.028839111328125, -0.00231170654296875, -0.06243896484375, -0.00424957275390625, -0.07525634765625, -0.0228271484375, 0.01371002197265625, 0.0147552490234375, -0.012969970703125, 0.02227783203125, 0.038970947265625, -0.05615234375, 0.042816162109375, -0.03759765625, 0.01806640625, -0.049652099609375, 0.059326171875, -0.03289794921875, 0.02410888671875, 0.0009441375732421875, 0.001171112060546875, -0.0114288330078125, -0.05084228515625, -0.0328369140625, 0.004352569580078125, 0.032135009765625, 0.02960205078125, -0.0244903564453125, 0.021270751953125, -0.039306640625, 0.0022296905517578125, 0.028778076171875, -0.01187896728515625, -0.0023651123046875, 0.00528717041015625, -0.01459503173828125, -0.0535888671875, 0.0197296142578125, -0.0201873779296875, 0.041595458984375, 0.016448974609375, -0.026519775390625, 0.007488250732421875, 0.0266265869140625, -0.0276336669921875, -0.045501708984375, 0.02178955078125, 0.0182647705078125, -0.0167694091796875, -0.0296783447265625, -0.0018672943115234375, -0.040618896484375, 0.002681732177734375, 0.009033203125, 0.015594482421875, -0.0133819580078125, 0.02728271484375, 0.01580810546875, 0.0458984375, 0.014190673828125, 0.0200653076171875, -0.005496978759765625, -0.01303863525390625, 0.04327392578125, 0.024932861328125, -0.0114288330078125, 0.005657196044921875, -0.0146331787109375, -0.016876220703125, 0.038299560546875, 0.01343536376953125, -0.007419586181640625, -0.05780029296875, 0.05767822265625, -0.0162506103515625, -0.041717529296875, 0.037384033203125, 0.0210418701171875, 0.0245361328125, -0.008026123046875, 0.01113128662109375, -0.0156402587890625, -0.0030498504638671875, -0.059295654296875, 0.026519775390625, -0.015777587890625, -0.040313720703125, 0.0821533203125, -0.0157318115234375, -0.00905609130859375, -0.02520751953125, -0.0180511474609375, -0.0246734619140625, -0.0169525146484375, 0.0004146099090576172, 0.046875, 0.0161590576171875, 0.0029850006103515625, 0.0278472900390625, 0.07220458984375, 0.005451202392578125, 0.0035228729248046875, 0.046478271484375, 0.02874755859375, 0.006317138671875, -0.01357269287109375, -0.055328369140625, -0.004901885986328125, 0.004894256591796875, 0.0137481689453125, -0.01751708984375, 0.028106689453125, 0.0008893013000488281, -0.0204315185546875, 0.0156097412109375, -0.0280303955078125, 0.01520538330078125, -0.07623291015625, 0.0023136138916015625, 0.01114654541015625, 0.0269927978515625, 0.01971435546875, -0.01263427734375, 0.001804351806640625, -0.04290771484375, 0.039947509765625, -0.01015472412109375, 0.02850341796875, -0.006153106689453125, -0.016021728515625, -0.03350830078125, 0.01024627685546875, -0.002872467041015625, 0.0021381378173828125, 0.00812530517578125, 0.038909912109375, -0.0062408447265625, -0.047760009765625, -0.024688720703125, -0.053558349609375, -0.036224365234375, -0.026123046875, 0.01192474365234375, 0.055755615234375, -0.031768798828125, 0.0066986083984375, -0.0718994140625, -0.00197601318359375, 0.010650634765625, 0.06573486328125, -0.0006313323974609375, -0.039306640625, 0.046112060546875, -0.0279693603515625, -0.022796630859375, 0.00521087646484375, 0.03948974609375, -0.0484619140625, -0.0027866363525390625, -0.038482666015625, 0.0001647472381591797, -0.0112762451171875, -0.005825042724609375, -0.0025196075439453125, -0.01763916015625, 0.0020313262939453125, 0.048980712890625, -0.004451751708984375, -0.031524658203125, 0.050628662109375, -0.00431060791015625, -0.00019299983978271484, 0.029815673828125, 0.001369476318359375, -0.0097198486328125, -0.00033783912658691406, -0.009063720703125, 0.04193115234375, 0.035491943359375, 0.0243377685546875, 0.01050567626953125, -0.0042266845703125, 0.0123138427734375, 0.01401519775390625, -0.01556396484375, 0.00811767578125, -0.017608642578125, 0.0160369873046875, 0.05072021484375, 0.0108642578125, -0.03271484375, -0.0278167724609375, -0.05645751953125, 0.004718780517578125, 0.0225372314453125, 0.026153564453125, -0.0491943359375, 0.039947509765625, -0.033660888671875, 0.045013427734375, 0.0249176025390625, -0.01174163818359375, 0.0201568603515625, 0.018585205078125, -0.020660400390625, 0.0343017578125, 0.0173492431640625, -0.053680419921875, -0.01018524169921875, 0.00946044921875, -0.035064697265625, 0.028472900390625, 0.01108551025390625, 0.01340484619140625, 0.07672119140625, 0.0247039794921875, 0.058074951171875, -0.026275634765625, 0.0248870849609375, -0.0135955810546875, -0.01261138916015625, 0.039306640625, 0.0015048980712890625, -0.0039215087890625, 0.036041259765625, 0.059478759765625, 0.0224609375, -0.0134124755859375, 0.004337310791015625, 0.03558349609375, -0.0155792236328125, 0.0635986328125, -0.053131103515625, -0.046966552734375, 0.02313232421875, 0.0270538330078125, -0.01399993896484375, 0.02984619140625, 0.01788330078125, 0.0253753662109375, 0.030426025390625, 0.0273895263671875, 0.0281829833984375, -0.03472900390625, 0.0094451904296875, -0.0058746337890625, 0.004558563232421875, -0.01305389404296875, 0.0391845703125, 0.0241546630859375, 0.00949859619140625, -0.0506591796875, 0.008758544921875, -0.0216217041015625, 0.0277557373046875, 0.033416748046875, 0.031158447265625, -0.0293121337890625, 0.0221099853515625, 0.007137298583984375, -0.033355712890625, 0.0355224609375, 0.0029506683349609375, 0.01177215576171875, 0.036163330078125, -0.0261077880859375, 0.0100250244140625, 0.055694580078125, 0.0165557861328125, -0.018341064453125, 0.01678466796875, 0.013824462890625, 0.0295257568359375, -0.00855255126953125, 0.057769775390625, 0.022705078125, 0.0015506744384765625, 0.0557861328125, -0.039154052734375, -0.051666259765625, 0.004131317138671875, -0.029449462890625, 0.007465362548828125, -0.017730712890625, 0.0245819091796875, 0.01080322265625, -0.0472412109375, 0.0377197265625, 0.002773284912109375, 0.031219482421875, -0.00484466552734375, -0.01593017578125, 0.01461029052734375, 0.0540771484375, 0.055816650390625, 0.0171661376953125, 0.020172119140625, -0.034393310546875, -0.00876617431640625, -0.01296234130859375, -0.0206146240234375, -0.00628662109375, 0.0364990234375, 0.04510498046875, -0.01012420654296875, 0.0033626556396484375, -0.0161285400390625, -0.0227203369140625, 0.00775909423828125, -0.027191162109375, 0.033599853515625, -0.038421630859375, -0.00537872314453125, -0.01226043701171875, 0.0433349609375, -0.01454925537109375, -0.0139312744140625, -0.01045989990234375, 0.00582122802734375, -0.00777435302734375, -0.0012722015380859375, -0.0357666015625, 0.0218353271484375, 0.00667572021484375, 0.002315521240234375, 0.00267791748046875, -0.0328369140625, -0.0257568359375, -0.04486083984375, -0.005035400390625, -0.055755615234375, 0.00908660888671875, -0.0275115966796875, 0.0182952880859375, 0.02203369140625, 0.031158447265625, 0.01529693603515625, -0.001514434814453125, -0.015716552734375, -0.012451171875, 0.030426025390625, -0.006267547607421875, -0.0230712890625, 0.05438232421875, 0.04022216796875, 0.058349609375, -0.026641845703125, -0.025421142578125, -0.002841949462890625, -0.00027561187744140625, -0.014617919921875, 0.0187835693359375, -0.0240478515625, 0.0162200927734375, -0.010406494140625, -0.035736083984375, -0.03778076171875, 0.01380157470703125, -0.01983642578125, -0.04266357421875, 0.004238128662109375, -0.0201568603515625, 0.157958984375, -0.0335693359375, 0.006343841552734375, -0.0014715194702148438, -0.0335693359375, -0.04364013671875, 0.0166473388671875, 0.006618499755859375, -0.018646240234375, 0.00836181640625, -0.006000518798828125, 0.05914306640625, -0.00826263427734375, 0.015533447265625, -0.054351806640625, -0.01070404052734375, 0.00649261474609375, -0.0306854248046875, 0.0234222412109375, 0.05474853515625, 0.005817413330078125, -0.006847381591796875, -0.0007023811340332031, 0.0270538330078125, -0.0022869110107421875, -0.0031948089599609375, 0.0103302001953125, -0.0021915435791015625, 0.0007100105285644531, -0.016693115234375, 0.01250457763671875, -0.01529693603515625, 0.0179290771484375, -0.01512908935546875, -0.00782012939453125, 0.00018310546875, 0.0223846435546875, -0.01357269287109375, -0.01227569580078125, -0.0207366943359375, -0.0460205078125, -0.03411865234375, -0.050140380859375, 0.00629425048828125, -0.006130218505859375, -0.004802703857421875, 0.00665283203125, 0.064697265625, -0.016510009765625, -0.0240325927734375, -0.043548583984375, -0.00960540771484375, 0.0200347900390625, 0.0231475830078125, -0.01395416259765625, 0.03094482421875, 0.018280029296875, 0.0250396728515625, -0.0084686279296875, -0.0131072998046875, 0.031524658203125, -0.0080718994140625, 0.0089111328125, -0.01464080810546875, -0.0037994384765625, 0.016937255859375, -0.04229736328125, 0.016845703125, 0.0106201171875, 0.0313720703125, 0.011505126953125, 0.00705718994140625, 0.00411224365234375, -0.0028820037841796875, -0.00399017333984375, 0.0030765533447265625, -0.01168060302734375, 0.0150909423828125, -0.031982421875, -0.0247344970703125, 0.02117919921875, -0.0270843505859375, -0.015777587890625, 0.049285888671875, 0.01358795166015625, -0.007213592529296875, 0.029296875, -0.035400390625, -0.0152130126953125, -0.0167083740234375, -0.002048492431640625, 0.01346588134765625, -0.003543853759765625, -0.0217437744140625, 0.0142822265625, 0.0045623779296875, 0.005657196044921875, 0.0156097412109375, 0.0404052734375, -0.03857421875, -0.00231170654296875, 0.0172271728515625, -0.0218048095703125, -0.0226593017578125, 0.0167999267578125, 0.06195068359375, -0.005889892578125, 0.031280517578125, 0.01509857177734375, -0.0110931396484375, -0.0264739990234375, 0.017242431640625, -0.041717529296875, -0.03472900390625, 0.003360748291015625, 0.031768798828125, -0.0115203857421875, 0.028533935546875, -0.00429534912109375, 0.0145263671875, 0.034698486328125, -0.01041412353515625, 0.01629638671875, -0.0078582763671875, -0.02655029296875, -0.01806640625, -0.00791168212890625, -0.0194091796875, -0.0233612060546875, -0.0011911392211914062, 0.01045989990234375, -0.00955963134765625, -0.0053863525390625, 0.0137481689453125, -0.00922393798828125, -0.0242462158203125, -0.0147705078125, -0.0024776458740234375, 0.015625, -0.021514892578125, 0.00728607177734375, 0.006214141845703125, 0.0196075439453125, 0.00473785400390625, -0.0031261444091796875, 0.0016193389892578125, 0.0261688232421875, 0.02276611328125, -0.0146942138671875, -0.03692626953125, -0.019927978515625, 0.040374755859375, 0.038482666015625, -0.03546142578125, 0.0121612548828125, 0.024261474609375, 0.0308380126953125, 0.01050567626953125, -0.00864410400390625, 0.0333251953125, 0.0115203857421875, 0.0243072509765625, 0.0104827880859375, -0.0005526542663574219, -0.01629638671875, -0.01351165771484375, 0.021148681640625, -0.0007739067077636719, -0.005340576171875, 0.029083251953125, -0.0100860595703125, -0.052581787109375, -0.042510986328125, -0.0038585662841796875, -0.0008134841918945312, 0.00757598876953125, 0.0216217041015625, -0.017425537109375, -0.023834228515625, -0.015045166015625, 0.01690673828125, -0.045501708984375, -0.0142364501953125, -0.01186370849609375, 0.0034885406494140625, -0.004222869873046875, 0.0184326171875, 0.0163116455078125, -0.00905609130859375, 0.042755126953125, 0.0484619140625, 0.023162841796875, -0.07244873046875, -0.00502777099609375, 0.0173492431640625, 0.0050506591796875, 0.004852294921875, -0.0226898193359375, -0.03607177734375, 0.00750732421875, 0.013885498046875, 0.006305694580078125, 0.0204620361328125, 0.005191802978515625, -0.030426025390625, -0.044708251953125, -0.046051025390625, 0.017822265625, 0.007717132568359375, 0.024810791015625, -0.0276641845703125, 0.004665374755859375, 0.00103759765625, -0.0155792236328125, -0.058319091796875, 0.0156707763671875, -0.01397705078125, -0.019134521484375, 0.00505828857421875, 0.00867462158203125, -0.046722412109375, -0.01488494873046875, -0.004932403564453125, 0.051025390625, 0.00475311279296875, 0.0006656646728515625, -0.007587432861328125, -0.0287322998046875, -0.032318115234375, 0.01009368896484375, 0.0172271728515625, -0.0196990966796875, -0.0191802978515625, 0.014801025390625, -0.0308380126953125, -0.005062103271484375, 0.0345458984375, 0.0140533447265625, -0.022857666015625, 0.0005183219909667969, -0.049285888671875, 0.0246124267578125, -0.0033416748046875, 0.0201416015625, 0.0224761962890625, 0.016082763671875, 0.0019254684448242188, 0.0238494873046875, 0.0014276504516601562, 0.0038127899169921875, -0.0204010009765625, -0.0266571044921875, -0.010986328125, 0.01308441162109375, -0.01296234130859375, -0.03326416015625, -0.0139617919921875, 0.017181396484375, 0.0110931396484375, -0.03326416015625, 0.022613525390625, 0.004550933837890625, 0.020050048828125, -0.0191802978515625, -0.02398681640625, -0.0225830078125, 0.01434326171875, -0.0158843994140625, -0.0085906982421875, -0.0219573974609375, -0.042724609375, 0.004505157470703125, 0.006805419921875, 0.0421142578125, 0.07098388671875, 0.0039825439453125, 0.0265960693359375, -0.01580810546875, -0.0098724365234375, -0.048095703125, -0.0059814453125, 0.0243377685546875, 0.01531219482421875, 0.02655029296875, 0.0290374755859375, -0.0075225830078125, -0.015533447265625, 0.016082763671875, 0.003314971923828125, 0.01544952392578125, -0.04473876953125, -0.057464599609375, 0.0350341796875, 0.0171356201171875, 0.01010894775390625, -0.0190277099609375, 0.005901336669921875, -0.03326416015625, 0.00971221923828125, -0.021087646484375, -0.006275177001953125, 0.018646240234375, 0.03564453125, -0.044281005859375, -0.03216552734375, 0.0010137557983398438, -0.0235137939453125, 0.00860595703125, 0.040435791015625, -0.004520416259765625, -0.001956939697265625, -0.022186279296875, -0.06591796875, 0.0014209747314453125, -0.0343017578125, -0.02655029296875, -0.01537322998046875, 0.006214141845703125, 0.01212310791015625, 0.041778564453125, -0.0157012939453125, -0.0076141357421875, 0.0298614501953125, -0.019622802734375, -0.01543426513671875, 0.019134521484375, -0.0009822845458984375, -0.00467681884765625, 0.0134429931640625, -0.0056304931640625, -0.02777099609375, -0.031402587890625, -0.028564453125, 0.005184173583984375, 0.0087127685546875, 0.0100250244140625, -0.036895751953125, -0.01059722900390625, -0.01593017578125, -0.0016813278198242188, 0.0040130615234375, -0.0009522438049316406, 0.0081634521484375, 0.007843017578125, 0.02996826171875, 0.01375579833984375, -0.0168304443359375, -0.0017538070678710938, -0.0172271728515625, 0.0009336471557617188, 0.02239990234375, -0.032867431640625, -0.0252685546875, -0.0096282958984375, -0.005664825439453125, 0.0279388427734375, 0.005962371826171875, 0.02581787109375, 0.018310546875, 0.0190582275390625, 0.0005826950073242188, -0.007656097412109375, 0.013031005859375, -0.00885009765625, 0.03240966796875, 0.024993896484375, -0.00334930419921875, 0.041259765625, -0.0131683349609375, 0.0078887939453125, -0.0129547119140625, 0.034637451171875, 0.0032024383544921875, -0.0157928466796875, -0.01166534423828125, -0.0108795166015625, -0.01422119140625, -0.0220794677734375, -0.036285400390625, 0.05908203125, 0.0166778564453125, -0.0228424072265625, 0.007648468017578125, 0.029693603515625, -0.0025806427001953125, 0.0008091926574707031, -0.0026702880859375, -0.036834716796875, 0.01015472412109375, 0.0196380615234375, 0.0167236328125, 0.0133209228515625, 0.006542205810546875, 0.01328277587890625, 0.04315185546875, 0.0209808349609375, 0.01384735107421875, 0.00685882568359375, 0.0292205810546875, -0.0156707763671875, 0.0038623809814453125, 0.0074615478515625, 0.043365478515625, 0.004337310791015625, 0.0072784423828125, 0.018951416015625, -0.0186309814453125, -0.006069183349609375, -0.014129638671875, -0.0302734375, 0.00881195068359375, 0.0035381317138671875, -0.004184722900390625, 0.00201416015625, 0.01222991943359375, -0.017181396484375, -0.0165252685546875, 0.0303497314453125, 0.01617431640625, 0.0048675537109375, -0.0318603515625, -0.07647705078125, 0.04290771484375, -0.01163482666015625, 0.039154052734375, 0.01064300537109375, -0.020416259765625, 0.007480621337890625, 0.0202178955078125, 0.005523681640625, -0.01824951171875, -0.032806396484375, 0.021514892578125, 0.05462646484375, 0.00580596923828125, -0.0380859375, -0.043426513671875, -0.02130126953125, -0.03033447265625, 0.00650787353515625, -0.002979278564453125, 0.045654296875, 0.0172882080078125, 0.0307464599609375, -0.00028252601623535156, -0.01404571533203125, 0.00923919677734375, -0.04931640625, 0.00243377685546875, 0.041259765625, 0.0262603759765625, 0.02044677734375, 0.00774383544921875, -0.005146026611328125, 0.01190185546875, -0.005016326904296875, -0.01312255859375, -0.04095458984375, -0.01279449462890625, 0.0194549560546875, -0.0262908935546875, -0.0071868896484375, 0.009857177734375, 0.0055389404296875, 0.001857757568359375, -0.025115966796875, -0.0531005859375, -0.002048492431640625, -0.0244293212890625, -0.006771087646484375, 0.0211334228515625, 0.012298583984375, -0.04132080078125, 0.00852203369140625, 0.004627227783203125, -0.02667236328125, 0.0081939697265625, 0.002349853515625, -0.0248870849609375, 0.0513916015625, 0.024322509765625, -0.0048675537109375, 0.0228271484375, -0.0169677734375, -0.00835418701171875, -0.0029697418212890625, -0.00963592529296875, 0.053131103515625, 0.034027099609375, -0.03118896484375, -0.00485992431640625, 0.01461029052734375, 0.0285186767578125, 0.01169586181640625, -0.03826904296875, 0.028717041015625, 0.0540771484375, -0.0093536376953125, 0.028564453125, 0.0323486328125, -0.021728515625, 0.0699462890625, 0.006439208984375, -0.0012187957763671875, 0.0226287841796875, 0.0019178390502929688, 0.0078582763671875, -0.0201416015625, 0.0638427734375

### Amazon data

In [25]:
poinstructs = []
for i, data in enumerate(data_to_embed):
    pointstruct = PointStruct(
        id=i,
        vector=get_embedding(data["description"]),
        payload=data,
    )
    poinstructs.append(pointstruct)

In [26]:
poinstructs

[PointStruct(id=0, vector=[0.0207977294921875, 0.001369476318359375, -0.017486572265625, 0.0015239715576171875, -0.0416259765625, -0.020050048828125, 0.025634765625, -0.0034580230712890625, 0.003925323486328125, -0.0195159912109375, 0.0098114013671875, 0.042388916015625, -0.051025390625, -0.0164337158203125, 0.0290679931640625, -0.0012540817260742188, -0.01528167724609375, 0.015380859375, -0.0183258056640625, -0.033477783203125, 0.001750946044921875, 0.038330078125, 0.01427459716796875, -0.04010009765625, 0.06414794921875, -0.007572174072265625, -0.007106781005859375, -0.01187896728515625, 0.0380859375, 0.02215576171875, -0.00417327880859375, -0.0528564453125, -0.0287322998046875, -0.0489501953125, -0.021148681640625, -0.0008411407470703125, -0.05029296875, -0.046661376953125, -0.0186767578125, 0.00664520263671875, 0.034027099609375, 0.042755126953125, 0.00943756103515625, 0.00830841064453125, -0.0279388427734375, -0.01495361328125, -0.06787109375, 0.0350341796875, -0.06658935546875, -0.0172119140625, -0.0560302734375, 0.023956298828125, -0.01214599609375, 0.0194091796875, -0.01245880126953125, -0.01172637939453125, 0.0099029541015625, -0.0020427703857421875, 0.00811004638671875, 0.0251617431640625, 0.01528167724609375, -0.0333251953125, 0.0206756591796875, -0.01690673828125, 0.06939697265625, -0.05035400390625, 0.004093170166015625, 0.012359619140625, 0.01410675048828125, -0.04229736328125, 0.045806884765625, -0.00872039794921875, -0.034515380859375, -0.01474761962890625, 0.0178985595703125, 0.103271484375, 0.0018987655639648438, -0.0305938720703125, -0.0018243789672851562, 0.025360107421875, -0.05328369140625, -0.0186920166015625, -0.0670166015625, -0.0018930435180664062, -0.0186309814453125, -0.04180908203125, -0.0152587890625, -0.07891845703125, -0.0168304443359375, 0.0008883476257324219, 0.0055084228515625, 0.050811767578125, -0.01490020751953125, -0.07586669921875, -0.0546875, 0.01451873779296875, -0.010772705078125, -0.01312255859375, 0.00814056396484375, 0.004634857177734375, 0.032073974609375, -0.0712890625, -0.0196380615234375, 0.015716552734375, -0.02886962890625, -0.0168304443359375, 0.00215911865234375, -0.03118896484375, 0.036956787109375, 0.0413818359375, -0.009246826171875, -0.02288818359375, -0.039794921875, 0.021026611328125, -0.00174713134765625, -0.08233642578125, 0.0180511474609375, 0.004116058349609375, -0.021759033203125, -0.0472412109375, -0.01511383056640625, 0.0170135498046875, 0.0016717910766601562, -0.033782958984375, 0.034820556640625, -0.0078582763671875, -0.0609130859375, 0.0103759765625, -0.0484619140625, 0.0126495361328125, -0.026824951171875, 0.004444122314453125, 0.0347900390625, -0.022918701171875, 0.001415252685546875, -0.0384521484375, 0.01702880859375, -0.0166015625, 0.00982666015625, -0.0222320556640625, 0.07550048828125, -0.0179443359375, -0.00897979736328125, 0.02691650390625, -0.015106201171875, 0.0304718017578125, -0.007038116455078125, -0.038970947265625, 0.004138946533203125, 0.025360107421875, 0.0249786376953125, -0.007205963134765625, -0.048736572265625, -0.0230255126953125, 0.0099334716796875, 0.02801513671875, 0.04736328125, 0.042022705078125, -0.02734375, 0.033782958984375, -0.017181396484375, -0.026641845703125, -0.016754150390625, -0.00194549560546875, -0.01424407958984375, 0.032928466796875, 0.021697998046875, -0.036285400390625, -0.093994140625, 0.0171356201171875, 0.03692626953125, 0.0181427001953125, 0.020538330078125, 0.0136260986328125, 0.0109405517578125, 0.01319122314453125, 0.0435791015625, -0.038543701171875, -0.004360198974609375, 0.0199127197265625, 0.01535797119140625, -0.03558349609375, 0.004886627197265625, -0.0042266845703125, 0.0067596435546875, 0.0032978057861328125, -0.025970458984375, 0.046142578125, -0.0094757080078125, 0.053619384765625, -0.049835205078125, 0.00994110107421875, -0.006072998046875, 0.007244110107421875, 0.0177764892578125, -0.028564453125, -0.02142333984375, -0.005401611328125, -0.0247344970703125, -0.01242828369140625, -0.02227783203125, -0.03509521484375, 0.002399444580078125, 0.01343536376953125, -0.0308685302734375, -0.0270538330078125, 0.021331787109375, 0.053131103515625, -0.031707763671875, 0.00142669677734375, 0.040191650390625, -0.01488494873046875, 0.02911376953125, -0.001178741455078125, -0.01432037353515625, 0.026519775390625, 0.01462554931640625, 0.00461578369140625, -0.0009288787841796875, 0.04730224609375, -0.033416748046875, 0.0310821533203125, 0.035675048828125, -0.02508544921875, -0.0172882080078125, -0.02056884765625, 0.00415802001953125, -0.037933349609375, -0.033477783203125, -0.0411376953125, -0.053985595703125, -0.021759033203125, -0.027099609375, 0.00928497314453125, 0.0170745849609375, -0.0181427001953125, 0.0278778076171875, -0.016082763671875, -0.01470184326171875, 0.00975799560546875, -0.0102691650390625, 0.004119873046875, -0.0276641845703125, 0.0178070068359375, 0.0135345458984375, -0.005084991455078125, 0.021453857421875, -0.04241943359375, -0.0306854248046875, -0.00359344482421875, 0.00786590576171875, 0.0310516357421875, 0.01322174072265625, -0.037139892578125, 0.021881103515625, 0.061248779296875, -0.036224365234375, 0.05389404296875, -0.02587890625, -0.018035888671875, 0.0275421142578125, 0.01132965087890625, 0.0174407958984375, -0.0401611328125, 0.0134735107421875, -0.0570068359375, 0.029541015625, -0.01454925537109375, 0.0167083740234375, 0.0288848876953125, 0.0179595947265625, -0.03399658203125, -0.0180511474609375, 0.041595458984375, -0.01393890380859375, 0.03143310546875, -0.02099609375, -0.00644683837890625, 0.0165252685546875, 0.01346588134765625, -0.0169219970703125, 0.0296173095703125, -0.01561737060546875, 0.01288604736328125, 0.009674072265625, -0.01093292236328125, 0.0307769775390625, -0.0191802978515625, -0.0186309814453125, -0.0006017684936523438, -0.0167694091796875, 0.0126495361328125, -0.043365478515625, -0.00951385498046875, -0.02911376953125, -0.00963592529296875, 0.0263214111328125, 0.036834716796875, -0.017364501953125, 4.941225051879883e-05, 0.03851318359375, 0.057220458984375, 0.002513885498046875, -0.024444580078125, -0.05194091796875, 0.07574462890625, -0.0224151611328125, 0.038604736328125, -0.01239013671875, -0.0282440185546875, -0.0193634033203125, 0.00396728515625, -0.01348876953125, -0.06695556640625, 0.0245361328125, -0.0218505859375, 0.01068115234375, -0.0194549560546875, 0.053009033203125, 0.010589599609375, 0.0321044921875, -0.0259552001953125, -0.020965576171875, -0.03076171875, 0.0145263671875, -0.0135650634765625, 0.024322509765625, 0.01117706298828125, 0.011688232421875, -0.056427001953125, -0.004474639892578125, 0.032196044921875, -0.0012502670288085938, -0.01358795166015625, 0.0244903564453125, -0.04534912109375, -0.041046142578125, -0.039581298828125, -0.05194091796875, 0.015960693359375, 0.003978729248046875, -0.023223876953125, -0.072998046875, 0.0301666259765625, 0.013641357421875, 0.005054473876953125, 0.0162200927734375, -0.01309967041015625, 0.0249176025390625, 0.0205230712890625, 0.0100860595703125, -0.033294677734375, 0.0107574462890625, 0.004657745361328125, -0.00220489501953125, -0.017120361328125, 0.00296783447265625, 0.03594970703125, -0.00899505615234375, 0.035369873046875, -0.0662841796875, 0.0408935546875, 0.021026611328125, -0.0010318756103515625, -0.0181884765625, 0.02777099609375, -0.055908203125, -0.000400543212890625, 0.0235595703125, 0.024322509765625, 0.043243408203125, 0.00848388671875, -0.0112762451171875, 0.0034961700439453125, -0.06903076171875, -0.0269927978515625, 0.0222320556640625, 0.027313232421875, -0.0173797607421875, -0.02862548828125, 0.005340576171875, -0.0011301040649414062, -0.009063720703125, 0.027069091796875, -0.00666046142578125, 0.02984619140625, -0.0170440673828125, 0.021881103515625, 0.006378173828125, -0.050933837890625, -0.03179931640625, 0.011199951171875, 0.02496337890625, -0.004512786865234375, -0.00850677490234375, 0.006137847900390625, 0.08099365234375, 0.0177154541015625, 0.016693115234375, -0.01324462890625, -0.01490020751953125, -0.0394287109375, -0.01080322265625, 0.05279541015625, -0.032623291015625, 0.036407470703125, 0.08795166015625, 0.003063201904296875, 0.0030155181884765625, -0.02471923828125, -0.009857177734375, -0.06976318359375, 0.00931549072265625, -0.0185394287109375, -0.020294189453125, 0.01169586181640625, -0.04052734375, -0.021728515625, 0.022705078125, -0.007781982421875, 0.053863525390625, -0.035125732421875, -0.0135345458984375, 0.034454345703125, -0.0222930908203125, 0.0160064697265625, -0.01546478271484375, -0.0089111328125, 0.046875, -0.052154541015625, -0.00792694091796875, 0.0136260986328125, 0.033111572265625, 0.04388427734375, -0.00597381591796875, -0.049102783203125, -0.10693359375, -0.03851318359375, 0.04022216796875, -0.007381439208984375, -0.00408172607421875, -0.0301971435546875, -0.0216827392578125, -0.037445068359375, 0.013946533203125, -0.017059326171875, -0.01971435546875, 0.07464599609375, -0.0045013427734375, 0.0257110595703125, -0.06658935546875, 0.0028324127197265625, -0.03704833984375, 0.05078125, -0.03466796875, -0.0297393798828125, 0.0172271728515625, -0.04547119140625, -0.039520263671875, 0.020599365234375, -0.01971435546875, 0.01328277587890625, -0.0073394775390625, 0.00489044189453125, 0.043701171875, 0.0281219482421875, -0.0053253173828125, 0.0287933349609375, 0.016082763671875, -0.0017137527465820312, 0.006137847900390625, 0.05029296875, 0.0230255126953125, 0.02960205078125, -0.008453369140625, -0.0345458984375, 0.04449462890625, 0.00414276123046875, -0.025054931640625, -0.0014705657958984375, -0.040557861328125, 0.015655517578125, -0.033050537109375, -0.00896453857421875, 0.020111083984375, 0.01849365234375, -0.00189208984375, 0.01337432861328125, 0.0246734619140625, -0.04229736328125, -0.017669677734375, 0.01036834716796875, 0.03131103515625, -0.004787445068359375, 0.01263427734375, -0.038360595703125, -0.047515869140625, -0.0006699562072753906, 0.007740020751953125, 0.0009212493896484375, 0.00629425048828125, -0.02166748046875, 0.00388336181640625, -0.0092620849609375, 0.0198974609375, 0.00444793701171875, -0.041656494140625, -0.02294921875, -0.00420379638671875, -0.004039764404296875, 0.055023193359375, 0.041259765625, 6.99758529663086e-05, 0.022125244140625, 0.01885986328125, 0.013916015625, 0.02685546875, 0.0450439453125, 0.00989532470703125, 0.01558685302734375, 0.0033740997314453125, -0.00714111328125, 0.053741455078125, 0.005542755126953125, -0.0281982421875, -0.0272979736328125, -0.0135498046875, -0.024169921875, -0.02392578125, 0.01316070556640625, -0.0204925537109375, 0.01108551025390625, -0.0236358642578125, -0.01090240478515625, 0.00843048095703125, 0.0170745849609375, -0.0165557861328125, 0.0005383491516113281, -0.03460693359375, 0.03240966796875, 0.04473876953125, -0.0170745849609375, -0.0016260147094726562, -0.02557373046875, 0.00672149658203125, 0.024261474609375, -0.03411865234375, 0.0246734619140625, -0.0175018310546875, 0.04119873046875, -0.0216217041015625, -0.0247955322265625, 0.0170440673828125, -0.013519287109375, 0.015625, 0.0111846923828125, 0.003040313720703125, 0.0010271072387695312, -0.019500732421875, 0.0173797607421875, 0.053619384765625, -0.035614013671875, -0.00048804283142089844, -0.0036144256591796875, 0.0012083053588867188, 0.0126495361328125, 0.0201416015625, -0.00926971435546875, -0.004871368408203125, 0.02923583984375, -0.01508331298828125, -0.0003457069396972656, 0.00301361083984375, 0.0005035400390625, -0.00963592529296875, 0.015045166015625, 0.01346588134765625, -0.0015239715576171875, -0.0059967041015625, 0.025848388671875, 0.002666473388671875, -0.02227783203125, 0.0178375244140625, 0.006641387939453125, -0.036529541015625, 0.0193023681640625, -0.002559661865234375, -0.0202484130859375, 0.034271240234375, 0.01184844970703125, 0.0296783447265625, -0.003376007080078125, -0.059661865234375, -0.0114288330078125, 0.00859832763671875, -0.000751495361328125, -0.0034027099609375, 0.005706787109375, -0.024505615234375, 0.00817108154296875, -0.004199981689453125, -0.02459716796875, 0.02496337890625, 0.01123809814453125, 0.007762908935546875, -0.0304718017578125, -0.0004916191101074219, -0.022613525390625, -0.0175323486328125, -0.0191650390625, -0.0267486572265625, 0.0184173583984375, 0.0509033203125, -0.0158538818359375, -0.0239410400390625, -0.0117034912109375, 0.01157379150390625, -0.0107421875, 0.00494384765625, -0.0162506103515625, -0.033660888671875, -0.01885986328125, 0.0301513671875, 0.01120758056640625, 0.023406982421875, 0.032196044921875, -0.052276611328125, -0.0531005859375, -0.00260162353515625, -0.025543212890625, -0.0196685791015625, -0.0109100341796875, 0.007343292236328125, -0.0193023681640625, 0.00926971435546875, -0.0021686553955078125, -0.004364013671875, -0.033905029296875, 0.039764404296875, -0.00920867919921875, 0.0129547119140625, 0.0421142578125, 0.0005373954772949219, 6.03795051574707e-05, 0.0309295654296875, 0.006778717041015625, -0.0269317626953125, -0.0229644775390625, -0.03961181640625, -0.0129241943359375, -0.004779815673828125, -0.026947021484375, -0.00838470458984375, 0.032318115234375, 0.002811431884765625, -0.0049591064453125, -0.0176849365234375, 0.025604248046875, -0.0016145706176757812, -0.01403045654296875, -0.0063934326171875, -0.0015459060668945312, -0.01270294189453125, -0.0077362060546875, 0.006561279296875, 0.01153564453125, 0.0009045600891113281, -0.0171966552734375, 0.00901031494140625, 0.013031005859375, 0.02410888671875, 0.02008056640625, -0.0074005126953125, -0.0003237724304199219, -0.0012674331665039062, -0.05615234375, 0.0611572265625, -0.01496124267578125, 0.019622802734375, 0.0166473388671875, 0.0011072158813476562, 0.043365478515625, -0.0276336669921875, -0.01629638671875, 0.004581451416015625, -0.0008268356323242188, -0.015838623046875, -0.003093719482421875, 0.0164794921875, 0.0229034423828125, -0.0120697021484375, -0.001293182373046875, -0.0009899139404296875, 0.014495849609375, -0.01428985595703125, -0.0036792755126953125, 0.022216796875, -0.01068878173828125, 0.0008440017700195312, 0.005344390869140625, -0.01263427734375, -0.020050048828125, 0.0022125244140625, -0.02825927734375, -0.01904296875, -0.014923095703125, -0.02752685546875, -0.019256591796875, 0.01031494140625, -0.002826690673828125, 0.01385498046875, -0.024169921875, -0.0163726806640625, -0.0013933181762695312, 0.0251617431640625, -0.02667236328125, -0.00804901123046875, 0.00037097930908203125, -0.0131072998046875, -0.0308380126953125, -0.00945281982421875, 0.0252227783203125, -0.0221710205078125, -0.0289764404296875, -0.0051116943359375, 0.004795074462890625, -0.015899658203125, -0.0029926300048828125, -0.01617431640625, -0.0025634765625, -0.01483154296875, -0.0014314651489257812, 0.0016756057739257812, 0.003154754638671875, -0.0190582275390625, 0.034454345703125, -0.0635986328125, 0.0094757080078125, -0.00885009765625, -0.023529052734375, -0.031494140625, 0.01403045654296875, -0.045684814453125, -0.0038471221923828125, 0.0252685546875, -0.011810302734375, 0.033355712890625, -0.04791259765625, -0.0184173583984375, -0.00925445556640625, 0.0009775161743164062, 0.0032958984375, -0.007205963134765625, -0.018218994140625, 0.0005035400390625, -0.02459716796875, -0.045440673828125, 0.0268096923828125, -0.02197265625, 0.00628662109375, -0.003063201904296875, -0.0179595947265625, 0.0002472400665283203, 0.042266845703125, -0.002895355224609375, -0.012542724609375, -0.046051025390625, 0.004383087158203125, -0.0419921875, 0.01386260986328125, 0.036163330078125, -0.03424072265625, -0.042999267578125, -0.0259552001953125, -0.05322265625, 0.03094482421875, -0.023834228515625, 0.0053558349609375, 0.03228759765625, 0.010711669921875, 0.00783538818359375, -0.001148223876953125, 0.00811004638671875, -0.004619598388671875, 0.021484375, 0.00782012939453125, 0.0276336669921875, -0.00067138671875, 0.0110015869140625, -0.012115478515625, -0.01157379150390625, -0.020172119140625, 0.02801513671875, -0.05072021484375, -0.0024318695068359375, -0.025543212890625, -0.0170135498046875, -0.0298309326171875, 0.0029697418212890625, 0.0206756591796875, 0.0213623046875, -0.007476806640625, -0.025238037109375, 0.032928466796875, -0.0088653564453125, -0.014404296875, -0.0177764892578125, 0.02081298828125, -0.00946044921875, 0.004184722900390625, -0.0097808837890625, 0.020843505859375, -0.033782958984375, 0.009857177734375, -0.03173828125, 0.02862548828125, 0.062164306640625, 0.007350921630859375, -0.015228271484375, -0.01514434814453125, 0.06829833984375, -0.017242431640625, -0.007549285888671875, -0.023101806640625, -0.011932373046875, 0.0200347900390625, -0.00638580322265625, 0.0013713836669921875, 0.0119781494140625, -0.04290771484375, 0.00943756103515625, -0.00919342041015625, -0.033599853515625, -0.0443115234375, 0.0010347366333007812, -0.01287841796875, 0.006015777587890625, 0.01145172119140625, -0.0232696533203125, -0.026031494140625, -0.00833892822265625, 0.011260986328125, -0.0181732177734375, 0.00942230224609375, -0.006000518798828125, -0.0109405517578125, 0.04833984375, 0.0189056396484375, 0.0123291015625, 0.02838134765625, -0.026947021484375, -0.004306793212890625, -0.00586700439453125, -0.01123809814453125, -0.00534820556640625, 0.0133209228515625, 0.01151275634765625, -0.02838134765625, 0.03521728515625, -0.025909423828125, -0.0216064453125, 0.007732391357421875, 0.01239776611328125, -0.021240234375, 0.0260772705078125, 0.036468505859375, -0.020599365234375, -0.039306640625, 0.01202392578125, 0.0159454345703125, -0.0305938720703125, 0.02105712890625, -0.0193328857421875, 0.00013720989227294922, 0.00220489501953125, 0.00018978118896484375, 0.01971435546875, 0.03076171875, -0.0308837890625, -0.008026123046875, -0.0175323486328125, -0.0013742446899414062, -0.0290679931640625, -0.019989013671875, -0.018218994140625, 0.051544189453125, -0.061614990234375, 0.01800537109375, 0.00843048095703125, -0.02691650390625, 0.00965118408203125, -0.044708251953125, 0.0208740234375, -0.00014328956604003906, -0.0291595458984375, 0.03021240234375, 0.007442474365234375, 0.03826904296875, -0.001613616943359375, 0.02581787109375, -0.01343536376953125, 0.00868988037109375, -0.034820556640625, -0.0011548995971679688, 0.00543975830078125, 0.001338958740234375, -0.005573272705078125, 0.024078369140625, -0.03228759765625, 0.0252227783203125, 0.023773193359375, -0.043212890625, 0.01187896728515625, -0.02203369140625, 0.0125274658203125, 0.00867462158203125, 0.004024505615234375, -0.0187225341796875, 0.016387939453125, -0.0175628662109375, 0.01910400390625, 0.0228271484375, 0.0229034423828125, 0.0020275115966796875, -0.0162200927734375, -0.01444244384765625, -0.01239013671875, 0.0280914306640625, 0.0244293212890625, 0.00930023193359375, -0.044677734375, 0.0115966796875, -0.033233642578125, 0.02593994140625, -0.0091400146484375, -0.042266845703125, 0.00550079345703125, -0.01300048828125, 0.0059967041015625, 0.00677490234375, 0.012542724609375, -0.0003390312194824219, 0.0200653076171875, -0.0299224853515625, -0.0124053955078125, -0.01459503173828125, 0.031829833984375, 0.0159149169921875, -0.04071044921875, -0.023406982421875, -0.01702880859375, -0.021331787109375, -0.0182037353515625, -0.01399993896484375, -0.0090484619140625, -0.00548553466796875, -0.00879669189453125, 0.02008056640625, 0.01708984375, 0.035736083984375, 0.02215576171875, -0.0033588409423828125, 0.0220947265625, -0.0406494140625, -0.0204010009765625, -0.00385284423828125, -0.01361846923828125, -0.042144775390625, 0.0755615234375, -0.01325225830078125, 0.0020275115966796875, 0.035919189453125, 0.004680633544921875, 0.01065826416015625, -0.0133819580078125, 0.0136260986328125, -0.056304931640625, -0.0030307769775390625, 0.009613037109375, -0.007663726806640625, 0.0172271728515625, 0.032562255859375, 0.0277252197265625, 0.0258941650390625, 0.0112762451171875, 0.0029773712158203125, 0.05096435546875, -0.0104827880859375, 0.0225372314453125, -0.00908660888671875, -0.038055419921875, -0.0129852294921875, 0.0421142578125, -0.0118255615234375, 0.02227783203125, 0.004405975341796875, 0.0121459

In [27]:
len(poinstructs)

50

### Write embedded data to qdrant

In [28]:
qdrant_client.upsert(
    collection_name="Amazon-items-collection-00",
    points=poinstructs,
    wait=True,
)

ResponseHandlingException: timed out

### Data retrieval function

In [32]:
def retrieve_data(query, top_k=5):
    query_embedding = get_embedding(query)
    search_result = qdrant_client.query_points(
        collection_name="Amazon-items-collection-00",
        query=query_embedding,
        limit=top_k,
    )
    return search_result

### Test Retrieval

In [34]:
retrieve_data("What kind of charging cords do you offer?",top_k=10).points

[ScoredPoint(id=10, version=1, score=0.37975973, payload={'description': 'Bauhoo Charging Station for Apple Multiple Devices, 3 in 1 Fast Wireless Charger Foldable iPhone 14/13/12/11/Pro/XS/Xs Max/XR/X/SE/8/8 Plus Watch 8/7/6/SE/5/4/3/2 AirPods 3/2/Pro with Adapter Pink 0', 'image': 'https://m.media-amazon.com/images/I/41iK0-+HVSL._AC_.jpg', 'rating_number': 159, 'price': 17.75, 'average_rating': 4.1, 'parent_asin': 'B0BHRHS1Q7'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1, version=1, score=0.36270505, payload={'description': '65W Replacement AC Adapter Charger for HP 15 15-f233wm 15-f272wm 15-f010wm 15-f305dx 15-af131dx Spectre X360 13-a010dx 13-4003dx 13-4103dx Pavilion 15 Laptop Notebook PC Power Supply Cord FEATURES / POWER SPECS : Only Pwr+ Chargers Have Extra Long 12 Ft Power AC/DC cords / Output 19.5V 3.33A 45W 65W / Input 100-240V / Made in Taiwan COMPATIBILITY: HP 14 15 17 M6 M7 Series 14-dq0040nr 463958-001 741727-001 740015-001 740015-003 740015-004 Envy Stream 11 13 14 PRO G2 HP Spectre x360 13 13T Split x2, 612 G1, 410 G1, Elite X2 1011 G1, x360 310 G2, ZBook 14 HP Chromebook 11 14 G1 G3 G4 Pavilion x360 14-dw1024nr; HP Notebook 15 17 Business Laptop 15-dy2024nr 15-af131dx 15-ay009dx 15-ay041wm 15-ba009dx 15-bs015dx 15-d035dx 15-f009wm 15-f010wm 15-f033wm 15-f039wm 15-f233wm 15-f272wm 15-f387wm 15-g070nr 15-r011dx 15-r029wm 15-r132wm COMPATIBILITY: HP Notebook 15, 17 Business Notebook 11-d010wm 11-d011wm 11-n010dx 13-c010nr 14-ax020wm 15-ac121dx 15-af131dx 15-ay009dx 15-ay039wm 15-ay041wm 15-d035dx 15-f009wm 15-f010wm 15-f033wm 15-f039wm 15-f211wm 15-f233wm 15-f271wm 15-f272wm 15-f305dx 15-f387wm 15-g019wm 15-g070nr 15-r011dx 15-r029wm 15-r132wm 15-bs289wm 15-f209wm 15-ba018wm 15-dy1074nr 15-cc067cl 15-cs0072wm COMPATIBILITY: P/N L24008-001 L25296-001 L25296-002 213349-109 710412-001 710413-001 719309-003 719309-001 721092-001 740015-001 740015-003 740015-004 740015-002 741727-001 741553-850 845836-850 854054-003 854054-002 854054-001 TPN-LA03 H6Y88AA H6Y89AA PA-1450-36HE PA-1650-32HE HSTNN-LA40 ADP-45FE B HSTNN-DA40 PPP009C PPP012L-E PPP012D-S SAFETY / UL LISTED: Tested, Approved and Certified by UL. UL number is unique. UL testing is authorized by OSHA - US Federal Agency / WARRANTY: 30 Days Refund - 24 Months Exchange. PWR+ is WA, USA based company. We are friendly Customer Support Experts', 'image': 'https://m.media-amazon.com/images/I/41xi8yPrvWL._AC_.jpg', 'rating_number': 1, 'price': 22.99, 'average_rating': 5.0, 'parent_asin': 'B008FPY1VG'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=8, version=1, score=0.3584295, payload={'description': 'New Lenovo 230w ac Adapter Compatible with Lenovo Legion 5 Charger for Lenovo Legion 5 7 5P C7 S7 Y540 Y545 Y740 Y730 Y900 Y910 Y920 Y7000 4X20E75111 GX20L29347 ADL230NDC3A ADL230NLC3A 💯Output: 20V 11.5A 230W Input:100V-240V 50-60Hz 💯Compatible With Lenovo T431s,T440,T440p,T440s,T450,T450s,T460,T460p,T460s,T470,T470p,T540p,T550,T560,T570,TP25.a.W550s, X1 Carbon (2nd Gen), X1 Carbon (3rd Gen) , X1 Carbon (4th Gen) , X1 Yoga (1st Gen) , X240,X240s ,X250,X260,P40 ,Yoga P50,P50s,P51,P51s,P70,P71.E440,E450,E455,E460,E465,E470,E475,E540,E550,E550c,E555,E560,E560p,E565,E570,E570p,E575,S1 Yoga 12, S3 Yoga 14,S5 Yoga 15,Yoga 14,Yoga 260,Yoga 460,L440,L450,L460,L540,L560,L570. 💯Compatible with Lenovo Ideapad Legion Y920 Y910 Y900 Y740 Y730 Y7000 Y545 Y540 5 5P C7 5-15ARH05H 5-15IMH05H 5-17IMH05H 5-17ARH05H 5P-15IMH05 5P-15IMH05H 5P-15ARH05H 7-15IMH05 7-15IMHg05 C7-15IMH05 81HE 81HH 81RJ 81SX 81SY 81Q6 81T2 Laptop 💯The 230W Charger provides strong protection against overheating, overcurrent, short circuit, overvoltage and overcharge.BULL-TECH 230W Charger has been tested, approved, and certified by Underwriter Laboratories. 💯Warranty: This product is eligible for replacement or refund within 30 days,and the manufacturer provides an additional 12 Months Warranty.', 'image': 'https://m.media-amazon.com/images/I/31O5105XuGL._AC_.jpg', 'rating_number': 10, 'price': None, 'average_rating': 2.8, 'parent_asin': 'B0BDRGBRN5'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=5, version=1, score=0.29288888, payload={'description': 'SNKIZN Universal Switching Power Supply - AC100-240V to DC5V10A, 50W Ideal for CCTV Camera Systems, Radio, LED Strip, Pixel Lights, Includes LED Driver 5V Power Supply The SNKIZN AC adapters provide protection features such as shortage protection, overload protection, and over-voltage protection (115%-135%). With an input range of 110V-220V 50/60Hz and output of 5V DC up to 30 Amps Max, the output voltage can be regulated by ±10%, from 4.5V to 5.5V. Made with high-quality raw materials, a porous metal shell, and excellent heat dissipation performance, the adapters are strong and suitable for indoor use. With automatic overload cut-off, over Voltage cut-off, automatic thermal cut-off, and short circuit protection, your electronic products are safe from destruction. Suitable for various 5V projects, such as WS2811 WS 2801 WS2812B SK6812 SK9822 APA102 LED Strip Pixel Light, CCTV Camera, Security System, Computer Project, etc.', 'image': 'https://m.media-amazon.com/images/I/41xpAE9UyQL._AC_.jpg', 'rating_number': 50, 'price': 14.99, 'average_rating': 4.6, 'parent_asin': 'B0CGFTRWX6'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=14, version=1, score=0.26638427, payload={'description': "Compressed Air Duster 6000mAh Battery - Electric Air Duster Addcolor AD-38 Keyboard Cleaner for Office-3 Adjustable Wind Speeds with LED Light, Cordless & Reusable Canned Air Duster for Computers 【⚡Air Duster with High Applicability】This compressed air duster can be widely used in your living room or bedroom/office/studio/car. You can use it when you want to clean the air conditioner, blinds and other corners that are hard to clean everyday; dust in your computer is not so easy to see, so you can use it to clean dust for your case and make sure your computer fan can work properly!! 【⚡One Air Duster for Multiple Uses】An electric air duster can contain multiple functions and achieve different results with the 5 accessories included. In addition to the nozzles with brushes for keyboard clean, you can also use the small inflatable nozzles to pump up the kids' swimming laps and the long nozzles to speed up the charcoal burning for family gatherings at the yard barbecue! ! Two nozzles at different heights can be used to quickly exhaust gas, for example for your airbed. 【⚡Great Replacement to Air Can Dusters】Compared to traditional disposable air canisters, the electronic duster offers 3 adjustable wind speeds: Gear 1-3: This means 51,000-100000 rotations per minute with (Max)50-25(Min) minutes of endurance; also, since it is rechargeable, it avoids environmental pollution from discarded canisters and more importantly saves the cost of buying air canisters time and time again.It is the great replacement to Air Can Dusters. 【⚡LED Lighting Design, Fast Charging】This air duster has a front LED light that provides good illumination when you need to clean a dark corner. The compressed air duster does not produce any liquid during use, so you can clean electronics such as keyboards or computer mainframes with confidence. Compared to most similar duster, we have added a fast charging feature, which means you only need to spend 2 hours to be fully charged quickly. 【⚡Cordless Design, Easy to Use】This AD-38 Electric Air Duster allows you to easily remove dust from the surface of objects，small size and lightweight（800g）, even ladies can hold it for long periods of time, this way you can easily clean your air conditioner or blinds more deeply, ensuring that it can be used around the house.Thanks to the built-in battery, no need to plug in, safety, efficient and convenient. It is equipped with a free storage bag that will not disrupt the order of your room. 【💖Tips for Use】: Before charging for the first time, you need to completely use off the power of the product (this will help the battery memory)", 'image': 'https://m.media-amazon.com/images/I/41PJXJasmFL._AC_.jpg', 'rating_number': 17, 'price': None, 'average_rating': 4.1, 'parent_asin': 'B0CB5VWJJS'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=38, version=1, score=0.26517832, payload={'description': 'Tucana Cute Glitter Airpods 3 Case for Women and Girls, Shining Bling Hard Case Compatible with Apple Airpods 3 Charging Case (Blue) Compatible: This case compatible for Apple AirPods 3rd Generation. It works well on both wireless and regular charger (AirPods are not included) Glitter Design: Beautiful color and glitter design looks very unique and fashionable. This shining case is ideal gift for girls and women Full Protection: Precision molded for snugly fitting without adding any bulk. The csae keeps your device safe from damage and scratches Easy to Carry: Cover includes a durable carabiner keychain easily attaches to your purse or belt loop. It enables you to have your AirPods 3 handy at all times, without fear of setting them down and losing them 2 Months Warranty: We assure you the best quality by offering 2 Months warranty. Any questions, please let us know and we will support asap', 'image': 'https://m.media-amazon.com/images/I/410IOrI-WtL._AC_.jpg', 'rating_number': 4, 'price': 6.99, 'average_rating': 4.6, 'parent_asin': 'B0B6ZNVP6R'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=40, version=1, score=0.25878075, payload={'description': '2 Pcs DC Voltage Reducer 48v to 12v Golf Cart 36v to 12v Converter, 10A 120W DC to DC Buck Converter 12 Volt Voltage Regulator Adjustable Voltage Stabilizer Transformer Power Supply for Club Car Light 96% High-Efficiency Golf Cart Voltage Reducer: this 12V dc buck converter has a high efficiency of up to 96%, which means it can convert more of the input power into usable output power, resulting in less energy waste and longer battery life for the golf cart. 30V-60V Wide Input Voltage Range: the 10A 120W dc-dc converter can accept a wide input voltage range of 30V-60V, making them suitable for both 36V and 48V to 12V converter golf carts. Stable Output Voltage: the 12v voltage regulator provides a stable 12V output voltage, which ensures a steady power supply to the golf cart\'s accessories, such as lights, radios, and other electrical devices; Efficient components and strong cooling reduce noise and heat Overload and Overheat Protection: the dc 12v converters are equipped with built-in overload and overheat protection mechanisms; This ensures that the converters automatically shut down or reduce the output power when they detect excessive load or temperature, preventing damage to the converters and the golf cart\'s electrical system Compact and Space-saving Design: the dc voltage regulator have a compact size 3"D x 3" x 1.3"H, allowing for easy installation in limited spaces within the golf cart; This makes them ideal for retrofitting or upgrading existing golf carts without requiring significant modifications Versatile Applications: apart from golf carts, these dc to dc converters can be used in various other applications that require a 12V power supply, such as electric scooters, electric bikes, RVs, boats, and more Waterproof and Shockproof: the 36 volt to 12 volt converter is designed to be waterproof and shockproof, which makes them durable and reliable in harsh outdoor environments', 'image': 'https://m.media-amazon.com/images/I/51E0Ct9UvfL.jpg', 'rating_number': 8, 'price': 24.99, 'average_rating': 4.8, 'parent_asin': 'B0C2QHKLVQ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=20, version=1, score=0.2549959, payload={'description': 'Winproo Armor Airpods Pro Case Cover with Lock Clip, Military Hard Shell Full-Body Shockproof Protective Case Skin with Keychain for Airpods Pro [Red] [Compatible with Airpods Pro Case] Winproo armor series\xa0Airpods Pro case cover is specially designed for Apple AirPods Pro charging case (2019 Released). PLEASE NOTE: Not compatible with AirPods 3rd & 2nd & 1st generation case [360-Degree Full-Body Case Protector] Sturdy Airpods Pro case hard shell is made of environmental friendly TPU material and shockproof protective corner design will definitely provide comprehensive protection for your Airpods Pro against daily drops, bumps and scratches [Convenient Charging] 2 pieces separated design make it easy to install and remove the case cover. Cool Airpods Pro case support both wired and wireless charging without removing the hard case cover. Charging LED light is visible during the charging [Airpods Pro Case with Lock Clip] Secure locking lid make sure the Airpods Pro case cover won’t opened accidently when carrying or dropping. Equipped with a metal carabiner keychain clip to help you conveniently carry your AirPods Pro anywhere [Reset Button Access] Reset button on the back of this hard AirPods Pro case allows you to reset or pair your Airpods Pro earbuds without taking out the charging case. [What You’ll Get] 1* Case Cover for Airpods Pro 2019, 1*Metal Carabiner Keychain Clip, 1*Spare Adhesive Tape, 1* Airpods Case Removal Tool (AirPods Pro &Charging Case are NOT included.)', 'image': 'https://m.media-amazon.com/images/I/41m2pqdfkqL._AC_.jpg', 'rating_number': 62, 'price': 11.99, 'average_rating': 4.1, 'parent_asin': 'B0B12HQ7WJ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=21, version=1, score=0.24106145, payload={'description': 'COO Small USB Desk Fan - 3 Speeds Powerful Airflow Fan, Small Mini Portable Fan for Home Office Bedroom Table & Desktop, Small Quiet Electric Fan 5 INCH - Black ✅【Small USB Desk Fan】This small USB fan design is compact and unique. Small sizes help save your desk space while providing a powerful Airflow fan. The ease of a small fan with the power you can feel from 2m away. ✅【3 Speed to Adjust】 This small USB fan has three different power fans to adjust. The most powerful speed can reach up to 2400, the wind can reach 3.8m/s, the middle speed is 2100rpm, the wind speed is 3.2m/s, the low speed is 1800rpm, and the wind speed is 2.5m/s. ✅【Multiple Power Supply】This small USB fan doesn’t need too much power and helps save your power fees, it can be powered by your laptop, power bank, and wall adapter. With these USB small fans, you don’t need to worry about the power is not enough. It can work 24 hours a day continuously. ✅【Low Noise】This mini USB fan is noiseless, the most high speed is only 50dB, and the lowest speed is below 30dB, it will not produce too much noise to interrupt your sleep, work, and study. The rubber map under the fans prevents the fans slip when the table is tilted. ✅【30 Degree Rotation】This small fan is designed with a 30-degree head rotation, it can adjust the suitable degree to fit different height tables, and provide the most suitable angle wind to quickly cool you down.', 'image': 'https://m.media-amazon.com/images/I/51DRA4BtpkL._AC_.jpg', 'rating_number': 68, 'price': 8.98, 'average_rating': 4.6, 'parent_asin': 'B0BYGYV9NX'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=31, version=1, score=0.23288766, payload={'description': "ABRRU Dual 5W Single USB Computer Speakers, PC Speakers for Desktop, Laptop Speakers with Crystal Clear Sound, Loud Volume, Volume Control and Mute Button(USB-C to USB Adapter Included)… 【Super Sound Quality】Our laptop speakers are built with two 3-inch all-magnetic speakers, which ensures that the speakers emit stunning sound quality with sufficient cavities.The high quality cable ensures stable transmission, which avoids the jerky sound that other Bluetooth speakers bring.Please note that due to the limitations of the cavity, our sound cannot be compared to some speakers with subwoofers in terms of bass 【Plug & Play】Our pc speakers are built with the latest decoder chips for 99% of the computer systems on the market, enabling plug and play.No need for driver software, No need for 3.5mm AUX cables.The single USB design avoids the hassle of cable management, allowing you to keep your desktop tidy while using as little space as possible on your desk 【Volume Control&Mute Button】The three buttons on the top of the speaker are the volume up/down and mute buttons. After consulting hundreds of buyers, they unanimously agreed that the one-touch mute function is more practical than the one-touch pause function. Because pause can only pause the sound of music software, but not stop the video and other sounds. So when you urgently need to stop playing sound, just press the mute button and you can do your things without worry 【Wider Compatibility】USB speakers with the latest built-in decoder chip are compatible with Windows, macOS and Chrome OS laptops and desktop computers, as long as they have the latest audio drivers installed for the sound card. USB C to USB Adapter in the box will make the speaker work well with Type-C port only devices like Samsung phones,Macbook Air,Pro,Huawei phones or other devices 【Perfect after-sales service】1-Years manufacturer's warranty, 2 months unconditional refund. Please trust our after-sales team, we do our best to make you feel the best service. If you have any questions, please check the manual or the box to contact us, we have a professional team to solve your problems within 12 hours", 'image': 'https://m.media-amazon.com/images/I/51Ao9NX4cfL._AC_.jpg', 'rating_number': 1890, 'price': 18.99, 'average_rating': 4.5, 'parent_asin': 'B0B28JML9P'}, vector=None, shard_key=None, order_value=None)]